# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import autoppia_backend_client
from autoppia_backend_client.api.health_check_api import HealthCheckApi  # noqa: E501
from autoppia_backend_client.rest import ApiException


class TestHealthCheckApi(unittest.TestCase):
    """HealthCheckApi unit test stubs"""

    def setUp(self):
        self.api = autoppia_backend_client.api.health_check_api.HealthCheckApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_health_check_list(self):
        """Test case for health_check_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
