# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import autoppia_backend_client
from autoppia_backend_client.models.worker_template import WorkerTemplate  # noqa: E501
from autoppia_backend_client.rest import ApiException

class TestWorkerTemplate(unittest.TestCase):
    """WorkerTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test WorkerTemplate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = autoppia_backend_client.models.worker_template.WorkerTemplate()  # noqa: E501
        if include_optional :
            return WorkerTemplate(
                id = 56, 
                developer = 56, 
                title = '0', 
                description = '0', 
                uploaded_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                favorited_by = [
                    56
                    ], 
                favorited_by_profiles = '0', 
                categories = [
                    56
                    ], 
                categories_name = '0', 
                image = '0', 
                docker_image = '0', 
                deployed_count = 56, 
                developers_profile = '0', 
                price = '0', 
                llm_provider = '0', 
                llm = '0', 
                integrations_categories = '0', 
                vectorstore_provider = '0', 
                agentic_framework = '0', 
                gpu = True, 
                gpu_type = '0', 
                demo_video = '0', 
                repo = '0', 
                config_yml = '0'
            )
        else :
            return WorkerTemplate(
                title = '0',
                description = '0',
                repo = '0',
        )

    def testWorkerTemplate(self):
        """Test WorkerTemplate"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
