# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import autoppia_backend_client
from autoppia_backend_client.models.user_configuration_extra_files import UserConfigurationExtraFiles  # noqa: E501
from autoppia_backend_client.rest import ApiException

class TestUserConfigurationExtraFiles(unittest.TestCase):
    """UserConfigurationExtraFiles unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UserConfigurationExtraFiles
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = autoppia_backend_client.models.user_configuration_extra_files.UserConfigurationExtraFiles()  # noqa: E501
        if include_optional :
            return UserConfigurationExtraFiles(
                id = 56,
                created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                user_configuration = 56,
                document = 56
            )
        else :
            return UserConfigurationExtraFiles(
        )

    def testUserConfigurationExtraFiles(self):
        """Test UserConfigurationExtraFiles"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
