# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import autoppia_backend_client
from autoppia_backend_client.api.payments_api import PaymentsApi  # noqa: E501
from autoppia_backend_client.rest import ApiException


class TestPaymentsApi(unittest.TestCase):
    """PaymentsApi unit test stubs"""

    def setUp(self):
        self.api = autoppia_backend_client.api.payments_api.PaymentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_payments_add_credit_create(self):
        """Test case for payments_add_credit_create

        """
        pass

    def test_payments_balance_create(self):
        """Test case for payments_balance_create

        """
        pass

    def test_payments_balance_reduce_create(self):
        """Test case for payments_balance_reduce_create

        """
        pass

    def test_payments_get_wallet_create(self):
        """Test case for payments_get_wallet_create

        """
        pass

    def test_payments_save_transaction_create(self):
        """Test case for payments_save_transaction_create

        """
        pass

    def test_payments_transaction_history_create(self):
        """Test case for payments_transaction_history_create

        """
        pass

    def test_payments_verify_wallet_create(self):
        """Test case for payments_verify_wallet_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
