# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import autoppia_backend_client
from autoppia_backend_client.models.embedding_database import EmbeddingDatabase  # noqa: E501
from autoppia_backend_client.rest import ApiException

class TestEmbeddingDatabase(unittest.TestCase):
    """EmbeddingDatabase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test EmbeddingDatabase
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = autoppia_backend_client.models.embedding_database.EmbeddingDatabase()  # noqa: E501
        if include_optional :
            return EmbeddingDatabase(
                id = 56, 
                documents = [
                    autoppia_backend_client.models.document.Document(
                        id = 56, 
                        user = 56, 
                        name = '0', 
                        file = '0', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        tags = [
                            56
                            ], 
                        s3_object_key = '0', 
                        open_ai_id = '0', )
                    ], 
                api_key = autoppia_backend_client.models.credential.Credential(
                    id = 56, 
                    user = 56, 
                    type = 'password', 
                    name = '0', 
                    credential = '0', ), 
                api_key_id = 56, 
                embedding_api_key = autoppia_backend_client.models.credential.Credential(
                    id = 56, 
                    user = 56, 
                    type = 'password', 
                    name = '0', 
                    credential = '0', ), 
                embedding_api_key_id = 56, 
                name = '0', 
                provider = 'INTERNAL', 
                index_name = '0', 
                openai_vector_store_id = '0', 
                user = 56
            )
        else :
            return EmbeddingDatabase(
                name = '0',
                provider = 'INTERNAL',
                user = 56,
        )

    def testEmbeddingDatabase(self):
        """Test EmbeddingDatabase"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
