# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import autoppia_backend_client
from autoppia_backend_client.api.apps_config_api import AppsConfigApi  # noqa: E501
from autoppia_backend_client.rest import ApiException


class TestAppsConfigApi(unittest.TestCase):
    """AppsConfigApi unit test stubs"""

    def setUp(self):
        self.api = autoppia_backend_client.api.apps_config_api.AppsConfigApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_apps_config_apps_create(self):
        """Test case for apps_config_apps_create

        """
        pass

    def test_apps_config_apps_delete(self):
        """Test case for apps_config_apps_delete

        """
        pass

    def test_apps_config_apps_deploy_info_list(self):
        """Test case for apps_config_apps_deploy_info_list

        """
        pass

    def test_apps_config_apps_deploy_list(self):
        """Test case for apps_config_apps_deploy_list

        """
        pass

    def test_apps_config_apps_deploy_stop_list(self):
        """Test case for apps_config_apps_deploy_stop_list

        """
        pass

    def test_apps_config_apps_list(self):
        """Test case for apps_config_apps_list

        """
        pass

    def test_apps_config_apps_partial_update(self):
        """Test case for apps_config_apps_partial_update

        """
        pass

    def test_apps_config_apps_read(self):
        """Test case for apps_config_apps_read

        """
        pass

    def test_apps_config_apps_update(self):
        """Test case for apps_config_apps_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
