# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import autoppia_backend_client
from autoppia_backend_client.api.workers_api import WorkersApi  # noqa: E501
from autoppia_backend_client.rest import ApiException


class TestWorkersApi(unittest.TestCase):
    """WorkersApi unit test stubs"""

    def setUp(self):
        self.api = autoppia_backend_client.api.workers_api.WorkersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_workers_configuration_category_create(self):
        """Test case for workers_configuration_category_create

        """
        pass

    def test_workers_configuration_category_delete(self):
        """Test case for workers_configuration_category_delete

        """
        pass

    def test_workers_configuration_category_list(self):
        """Test case for workers_configuration_category_list

        """
        pass

    def test_workers_configuration_category_partial_update(self):
        """Test case for workers_configuration_category_partial_update

        """
        pass

    def test_workers_configuration_category_read(self):
        """Test case for workers_configuration_category_read

        """
        pass

    def test_workers_configuration_category_update(self):
        """Test case for workers_configuration_category_update

        """
        pass

    def test_workers_configuration_prompt_category_create(self):
        """Test case for workers_configuration_prompt_category_create

        """
        pass

    def test_workers_configuration_prompt_category_delete(self):
        """Test case for workers_configuration_prompt_category_delete

        """
        pass

    def test_workers_configuration_prompt_category_list(self):
        """Test case for workers_configuration_prompt_category_list

        """
        pass

    def test_workers_configuration_prompt_category_partial_update(self):
        """Test case for workers_configuration_prompt_category_partial_update

        """
        pass

    def test_workers_configuration_prompt_category_read(self):
        """Test case for workers_configuration_prompt_category_read

        """
        pass

    def test_workers_configuration_prompt_category_update(self):
        """Test case for workers_configuration_prompt_category_update

        """
        pass

    def test_workers_configuration_prompt_create(self):
        """Test case for workers_configuration_prompt_create

        """
        pass

    def test_workers_configuration_prompt_delete(self):
        """Test case for workers_configuration_prompt_delete

        """
        pass

    def test_workers_configuration_prompt_list(self):
        """Test case for workers_configuration_prompt_list

        """
        pass

    def test_workers_configuration_prompt_partial_update(self):
        """Test case for workers_configuration_prompt_partial_update

        """
        pass

    def test_workers_configuration_prompt_read(self):
        """Test case for workers_configuration_prompt_read

        """
        pass

    def test_workers_configuration_prompt_update(self):
        """Test case for workers_configuration_prompt_update

        """
        pass

    def test_workers_configuration_result_create(self):
        """Test case for workers_configuration_result_create

        """
        pass

    def test_workers_configuration_result_delete(self):
        """Test case for workers_configuration_result_delete

        """
        pass

    def test_workers_configuration_result_list(self):
        """Test case for workers_configuration_result_list

        """
        pass

    def test_workers_configuration_result_partial_update(self):
        """Test case for workers_configuration_result_partial_update

        """
        pass

    def test_workers_configuration_result_read(self):
        """Test case for workers_configuration_result_read

        """
        pass

    def test_workers_configuration_result_update(self):
        """Test case for workers_configuration_result_update

        """
        pass

    def test_workers_configuration_tasks_create(self):
        """Test case for workers_configuration_tasks_create

        """
        pass

    def test_workers_configuration_tasks_delete(self):
        """Test case for workers_configuration_tasks_delete

        """
        pass

    def test_workers_configuration_tasks_list(self):
        """Test case for workers_configuration_tasks_list

        """
        pass

    def test_workers_configuration_tasks_partial_update(self):
        """Test case for workers_configuration_tasks_partial_update

        """
        pass

    def test_workers_configuration_tasks_read(self):
        """Test case for workers_configuration_tasks_read

        """
        pass

    def test_workers_configuration_tasks_update(self):
        """Test case for workers_configuration_tasks_update

        """
        pass

    def test_workers_configuration_tests_create(self):
        """Test case for workers_configuration_tests_create

        """
        pass

    def test_workers_configuration_tests_delete(self):
        """Test case for workers_configuration_tests_delete

        """
        pass

    def test_workers_configuration_tests_list(self):
        """Test case for workers_configuration_tests_list

        """
        pass

    def test_workers_configuration_tests_partial_update(self):
        """Test case for workers_configuration_tests_partial_update

        """
        pass

    def test_workers_configuration_tests_read(self):
        """Test case for workers_configuration_tests_read

        """
        pass

    def test_workers_configuration_tests_update(self):
        """Test case for workers_configuration_tests_update

        """
        pass

    def test_workers_configuration_worker_create(self):
        """Test case for workers_configuration_worker_create

        """
        pass

    def test_workers_configuration_worker_delete(self):
        """Test case for workers_configuration_worker_delete

        """
        pass

    def test_workers_configuration_worker_list(self):
        """Test case for workers_configuration_worker_list

        """
        pass

    def test_workers_configuration_worker_partial_update(self):
        """Test case for workers_configuration_worker_partial_update

        """
        pass

    def test_workers_configuration_worker_read(self):
        """Test case for workers_configuration_worker_read

        """
        pass

    def test_workers_configuration_worker_update(self):
        """Test case for workers_configuration_worker_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
