# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import autoppia_backend_client
from autoppia_backend_client.api.llms_api import LlmsApi  # noqa: E501
from autoppia_backend_client.rest import ApiException


class TestLlmsApi(unittest.TestCase):
    """LlmsApi unit test stubs"""

    def setUp(self):
        self.api = autoppia_backend_client.api.llms_api.LlmsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_llms_llm_create(self):
        """Test case for llms_llm_create

        """
        pass

    def test_llms_llm_delete(self):
        """Test case for llms_llm_delete

        """
        pass

    def test_llms_llm_list(self):
        """Test case for llms_llm_list

        """
        pass

    def test_llms_llm_partial_update(self):
        """Test case for llms_llm_partial_update

        """
        pass

    def test_llms_llm_provider_create(self):
        """Test case for llms_llm_provider_create

        """
        pass

    def test_llms_llm_provider_delete(self):
        """Test case for llms_llm_provider_delete

        """
        pass

    def test_llms_llm_provider_list(self):
        """Test case for llms_llm_provider_list

        """
        pass

    def test_llms_llm_provider_partial_update(self):
        """Test case for llms_llm_provider_partial_update

        """
        pass

    def test_llms_llm_provider_read(self):
        """Test case for llms_llm_provider_read

        """
        pass

    def test_llms_llm_provider_update(self):
        """Test case for llms_llm_provider_update

        """
        pass

    def test_llms_llm_read(self):
        """Test case for llms_llm_read

        """
        pass

    def test_llms_llm_update(self):
        """Test case for llms_llm_update

        """
        pass

    def test_llms_user_llm_create(self):
        """Test case for llms_user_llm_create

        """
        pass

    def test_llms_user_llm_delete(self):
        """Test case for llms_user_llm_delete

        """
        pass

    def test_llms_user_llm_list(self):
        """Test case for llms_user_llm_list

        """
        pass

    def test_llms_user_llm_partial_update(self):
        """Test case for llms_user_llm_partial_update

        """
        pass

    def test_llms_user_llm_read(self):
        """Test case for llms_user_llm_read

        """
        pass

    def test_llms_user_llm_update(self):
        """Test case for llms_user_llm_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
