# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import autoppia_backend_client
from autoppia_backend_client.models.template import Template  # noqa: E501
from autoppia_backend_client.rest import ApiException

class TestTemplate(unittest.TestCase):
    """Template unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Template
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = autoppia_backend_client.models.template.Template()  # noqa: E501
        if include_optional :
            return Template(
                id = 56,
                name = '0',
                description = '0',
                created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                price = '0',
                integration_categories = None,
                source = '0',
                user = autoppia_backend_client.models.user.User(
                    id = 56,
                    first_name = '0',
                    last_name = '0',
                    email = '0',
                    username = '0',
                    title = '0',
                    company = '0',
                    about = '0',
                    phone_num = '0',
                    country = '0',
                    language = '0',
                    is_allowed_in_dashboard = True,
                    messages_left = 56, ),
                user_id = 56,
                is_favorite = '0',
                favorite_count = '0'
            )
        else :
            return Template(
                name = '0',
                description = '0',
                source = '0',
        )

    def testTemplate(self):
        """Test Template"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
