# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import autoppia_backend_client
from autoppia_backend_client.models.user_llm_model import UserLLMModel  # noqa: E501
from autoppia_backend_client.rest import ApiException

class TestUserLLMModel(unittest.TestCase):
    """UserLLMModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UserLLMModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = autoppia_backend_client.models.user_llm_model.UserLLMModel()  # noqa: E501
        if include_optional :
            return UserLLMModel(
                id = 56, 
                llm_model = autoppia_backend_client.models.llm_model.LLMModel(
                    id = 56, 
                    provider = autoppia_backend_client.models.llm_provider.LLMProvider(
                        id = 56, 
                        name = '0', 
                        description = '0', 
                        provider_type = 'ANTHROPIC', ), 
                    provider_id = 56, 
                    name = '0', 
                    description = '0', 
                    open_source = True, 
                    cost_per_1000_tokens = 1.337, 
                    available = True, 
                    image_url = '0', ), 
                llm_model_id = 56, 
                api_key = autoppia_backend_client.models.credential.Credential(
                    id = 56, 
                    user = 56, 
                    type = 'password', 
                    name = '0', 
                    credential = '0', ), 
                api_key_id = 56, 
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                active = True, 
                user = 56
            )
        else :
            return UserLLMModel(
                user = 56,
        )

    def testUserLLMModel(self):
        """Test UserLLMModel"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
