# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import autoppia_backend_client
from autoppia_backend_client.models.token_refresh import TokenRefresh  # noqa: E501
from autoppia_backend_client.rest import ApiException

class TestTokenRefresh(unittest.TestCase):
    """TokenRefresh unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TokenRefresh
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = autoppia_backend_client.models.token_refresh.TokenRefresh()  # noqa: E501
        if include_optional :
            return TokenRefresh(
                refresh = '0',
                access = '0'
            )
        else :
            return TokenRefresh(
                refresh = '0',
        )

    def testTokenRefresh(self):
        """Test TokenRefresh"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
