# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import autoppia_backend_client
from autoppia_backend_client.models.mcp import MCP  # noqa: E501
from autoppia_backend_client.rest import ApiException

class TestMCP(unittest.TestCase):
    """MCP unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MCP
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = autoppia_backend_client.models.mcp.MCP()  # noqa: E501
        if include_optional :
            return MCP(
                id = 56, 
                headers = [
                    autoppia_backend_client.models.mcp_header.MCPHeader(
                        id = 56, 
                        key = '0', 
                        value = '0', )
                    ], 
                name = '0', 
                description = '0', 
                transport = 'SSE', 
                url = '0', 
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                user = 56
            )
        else :
            return MCP(
                name = '0',
                description = '0',
                transport = 'SSE',
                url = '0',
                user = 56,
        )

    def testMCP(self):
        """Test MCP"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
