# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import autoppia_backend_client
from autoppia_backend_client.api.teams_api import TeamsApi  # noqa: E501
from autoppia_backend_client.rest import ApiException


class TestTeamsApi(unittest.TestCase):
    """TeamsApi unit test stubs"""

    def setUp(self):
        self.api = autoppia_backend_client.api.teams_api.TeamsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_teams_create(self):
        """Test case for teams_create

        """
        pass

    def test_teams_delete(self):
        """Test case for teams_delete

        """
        pass

    def test_teams_list(self):
        """Test case for teams_list

        """
        pass

    def test_teams_partial_update(self):
        """Test case for teams_partial_update

        """
        pass

    def test_teams_read(self):
        """Test case for teams_read

        """
        pass

    def test_teams_update(self):
        """Test case for teams_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
