# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import autoppia_backend_client
from autoppia_backend_client.models.list_user_integration_attribute import ListUserIntegrationAttribute  # noqa: E501
from autoppia_backend_client.rest import ApiException

class TestListUserIntegrationAttribute(unittest.TestCase):
    """ListUserIntegrationAttribute unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ListUserIntegrationAttribute
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = autoppia_backend_client.models.list_user_integration_attribute.ListUserIntegrationAttribute()  # noqa: E501
        if include_optional :
            return ListUserIntegrationAttribute(
                id = 56, 
                user_integration = 56, 
                integration_attribute = 56, 
                integration_attribute_obj = autoppia_backend_client.models.list_integration_attribute.ListIntegrationAttribute(
                    id = 56, 
                    integration = 56, 
                    name = '0', 
                    description = '0', 
                    variable_type = 'string', 
                    required = True, 
                    is_credential = True, 
                    credential_type = 'password', 
                    credential_name = '0', 
                    editable = True, 
                    default_value = '0', 
                    is_document = True, ), 
                value = '0', 
                credential = 56, 
                credential_obj = autoppia_backend_client.models.credential.Credential(
                    id = 56, 
                    user = 56, 
                    type = 'password', 
                    name = '0', 
                    credential = '0', ), 
                document = 56
            )
        else :
            return ListUserIntegrationAttribute(
                id = 56,
                user_integration = 56,
                integration_attribute = 56,
                integration_attribute_obj = autoppia_backend_client.models.list_integration_attribute.ListIntegrationAttribute(
                    id = 56, 
                    integration = 56, 
                    name = '0', 
                    description = '0', 
                    variable_type = 'string', 
                    required = True, 
                    is_credential = True, 
                    credential_type = 'password', 
                    credential_name = '0', 
                    editable = True, 
                    default_value = '0', 
                    is_document = True, ),
                value = '0',
        )

    def testListUserIntegrationAttribute(self):
        """Test ListUserIntegrationAttribute"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
