# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import autoppia_backend_client
from autoppia_backend_client.models.integration import Integration  # noqa: E501
from autoppia_backend_client.rest import ApiException

class TestIntegration(unittest.TestCase):
    """Integration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Integration
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = autoppia_backend_client.models.integration.Integration()  # noqa: E501
        if include_optional :
            return Integration(
                id = 56,
                name = '0',
                image_url = '0',
                category = 'social',
                unique = True
            )
        else :
            return Integration(
                name = '0',
                image_url = '0',
                category = 'social',
        )

    def testIntegration(self):
        """Test Integration"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
