# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import autoppia_backend_client
from autoppia_backend_client.api.documents_api import DocumentsApi  # noqa: E501
from autoppia_backend_client.rest import ApiException


class TestDocumentsApi(unittest.TestCase):
    """DocumentsApi unit test stubs"""

    def setUp(self):
        self.api = autoppia_backend_client.api.documents_api.DocumentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_documents_documents_create(self):
        """Test case for documents_documents_create

        """
        pass

    def test_documents_documents_delete(self):
        """Test case for documents_documents_delete

        """
        pass

    def test_documents_documents_list(self):
        """Test case for documents_documents_list

        """
        pass

    def test_documents_documents_partial_update(self):
        """Test case for documents_documents_partial_update

        """
        pass

    def test_documents_documents_read(self):
        """Test case for documents_documents_read

        """
        pass

    def test_documents_documents_update(self):
        """Test case for documents_documents_update

        """
        pass

    def test_documents_download_read(self):
        """Test case for documents_download_read

        """
        pass

    def test_documents_embedding_databases_create(self):
        """Test case for documents_embedding_databases_create

        """
        pass

    def test_documents_embedding_databases_delete(self):
        """Test case for documents_embedding_databases_delete

        """
        pass

    def test_documents_embedding_databases_list(self):
        """Test case for documents_embedding_databases_list

        """
        pass

    def test_documents_embedding_databases_partial_update(self):
        """Test case for documents_embedding_databases_partial_update

        """
        pass

    def test_documents_embedding_databases_read(self):
        """Test case for documents_embedding_databases_read

        """
        pass

    def test_documents_embedding_databases_update(self):
        """Test case for documents_embedding_databases_update

        """
        pass

    def test_documents_embeddings_create(self):
        """Test case for documents_embeddings_create

        """
        pass

    def test_documents_embeddings_delete(self):
        """Test case for documents_embeddings_delete

        """
        pass

    def test_documents_embeddings_list(self):
        """Test case for documents_embeddings_list

        """
        pass

    def test_documents_embeddings_partial_update(self):
        """Test case for documents_embeddings_partial_update

        """
        pass

    def test_documents_embeddings_read(self):
        """Test case for documents_embeddings_read

        """
        pass

    def test_documents_embeddings_update(self):
        """Test case for documents_embeddings_update

        """
        pass

    def test_documents_tags_create(self):
        """Test case for documents_tags_create

        """
        pass

    def test_documents_tags_delete(self):
        """Test case for documents_tags_delete

        """
        pass

    def test_documents_tags_list(self):
        """Test case for documents_tags_list

        """
        pass

    def test_documents_tags_partial_update(self):
        """Test case for documents_tags_partial_update

        """
        pass

    def test_documents_tags_read(self):
        """Test case for documents_tags_read

        """
        pass

    def test_documents_tags_update(self):
        """Test case for documents_tags_update

        """
        pass

    def test_documents_tracking_vs_create(self):
        """Test case for documents_tracking_vs_create

        """
        pass

    def test_documents_tracking_vs_delete(self):
        """Test case for documents_tracking_vs_delete

        """
        pass

    def test_documents_tracking_vs_list(self):
        """Test case for documents_tracking_vs_list

        """
        pass

    def test_documents_tracking_vs_partial_update(self):
        """Test case for documents_tracking_vs_partial_update

        """
        pass

    def test_documents_tracking_vs_read(self):
        """Test case for documents_tracking_vs_read

        """
        pass

    def test_documents_tracking_vs_update(self):
        """Test case for documents_tracking_vs_update

        """
        pass

    def test_documents_upload_create(self):
        """Test case for documents_upload_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
