# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from autoppia_backend_client.configuration import Configuration


class Document(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'user': 'int',
        'name': 'str',
        'file': 'str',
        'created_at': 'datetime',
        'updated_at': 'datetime',
        'tags': 'list[int]',
        's3_object_key': 'str',
        'open_ai_id': 'str'
    }

    attribute_map = {
        'id': 'id',
        'user': 'user',
        'name': 'name',
        'file': 'file',
        'created_at': 'created_at',
        'updated_at': 'updated_at',
        'tags': 'tags',
        's3_object_key': 's3_object_key',
        'open_ai_id': 'open_ai_id'
    }

    def __init__(self, id=None, user=None, name=None, file=None, created_at=None, updated_at=None, tags=None, s3_object_key=None, open_ai_id=None, local_vars_configuration=None):  # noqa: E501
        """Document - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._user = None
        self._name = None
        self._file = None
        self._created_at = None
        self._updated_at = None
        self._tags = None
        self._s3_object_key = None
        self._open_ai_id = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if user is not None:
            self.user = user
        self.name = name
        if file is not None:
            self.file = file
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at
        if tags is not None:
            self.tags = tags
        self.s3_object_key = s3_object_key
        self.open_ai_id = open_ai_id

    @property
    def id(self):
        """Gets the id of this Document.  # noqa: E501


        :return: The id of this Document.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Document.


        :param id: The id of this Document.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def user(self):
        """Gets the user of this Document.  # noqa: E501


        :return: The user of this Document.  # noqa: E501
        :rtype: int
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this Document.


        :param user: The user of this Document.  # noqa: E501
        :type: int
        """

        self._user = user

    @property
    def name(self):
        """Gets the name of this Document.  # noqa: E501


        :return: The name of this Document.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Document.


        :param name: The name of this Document.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) > 100):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `100`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def file(self):
        """Gets the file of this Document.  # noqa: E501


        :return: The file of this Document.  # noqa: E501
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this Document.


        :param file: The file of this Document.  # noqa: E501
        :type: str
        """

        self._file = file

    @property
    def created_at(self):
        """Gets the created_at of this Document.  # noqa: E501


        :return: The created_at of this Document.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this Document.


        :param created_at: The created_at of this Document.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this Document.  # noqa: E501


        :return: The updated_at of this Document.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this Document.


        :param updated_at: The updated_at of this Document.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def tags(self):
        """Gets the tags of this Document.  # noqa: E501


        :return: The tags of this Document.  # noqa: E501
        :rtype: list[int]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this Document.


        :param tags: The tags of this Document.  # noqa: E501
        :type: list[int]
        """

        self._tags = tags

    @property
    def s3_object_key(self):
        """Gets the s3_object_key of this Document.  # noqa: E501


        :return: The s3_object_key of this Document.  # noqa: E501
        :rtype: str
        """
        return self._s3_object_key

    @s3_object_key.setter
    def s3_object_key(self, s3_object_key):
        """Sets the s3_object_key of this Document.


        :param s3_object_key: The s3_object_key of this Document.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                s3_object_key is not None and len(s3_object_key) > 255):
            raise ValueError("Invalid value for `s3_object_key`, length must be less than or equal to `255`")  # noqa: E501

        self._s3_object_key = s3_object_key

    @property
    def open_ai_id(self):
        """Gets the open_ai_id of this Document.  # noqa: E501


        :return: The open_ai_id of this Document.  # noqa: E501
        :rtype: str
        """
        return self._open_ai_id

    @open_ai_id.setter
    def open_ai_id(self, open_ai_id):
        """Sets the open_ai_id of this Document.


        :param open_ai_id: The open_ai_id of this Document.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                open_ai_id is not None and len(open_ai_id) > 100):
            raise ValueError("Invalid value for `open_ai_id`, length must be less than or equal to `100`")  # noqa: E501

        self._open_ai_id = open_ai_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Document):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Document):
            return True

        return self.to_dict() != other.to_dict()
