# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from autoppia_backend_client.configuration import Configuration


class EmbeddingDatabase(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'documents': 'list[Document]',
        'api_key': 'Credential',
        'api_key_id': 'int',
        'embedding_api_key': 'Credential',
        'embedding_api_key_id': 'int',
        'name': 'str',
        'provider': 'str',
        'index_name': 'str',
        'openai_vector_store_id': 'str',
        'user': 'int'
    }

    attribute_map = {
        'id': 'id',
        'documents': 'documents',
        'api_key': 'api_key',
        'api_key_id': 'api_key_id',
        'embedding_api_key': 'embedding_api_key',
        'embedding_api_key_id': 'embedding_api_key_id',
        'name': 'name',
        'provider': 'provider',
        'index_name': 'index_name',
        'openai_vector_store_id': 'openai_vector_store_id',
        'user': 'user'
    }

    def __init__(self, id=None, documents=None, api_key=None, api_key_id=None, embedding_api_key=None, embedding_api_key_id=None, name=None, provider=None, index_name=None, openai_vector_store_id=None, user=None, local_vars_configuration=None):  # noqa: E501
        """EmbeddingDatabase - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._documents = None
        self._api_key = None
        self._api_key_id = None
        self._embedding_api_key = None
        self._embedding_api_key_id = None
        self._name = None
        self._provider = None
        self._index_name = None
        self._openai_vector_store_id = None
        self._user = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if documents is not None:
            self.documents = documents
        if api_key is not None:
            self.api_key = api_key
        if api_key_id is not None:
            self.api_key_id = api_key_id
        if embedding_api_key is not None:
            self.embedding_api_key = embedding_api_key
        if embedding_api_key_id is not None:
            self.embedding_api_key_id = embedding_api_key_id
        self.name = name
        self.provider = provider
        self.index_name = index_name
        self.openai_vector_store_id = openai_vector_store_id
        self.user = user

    @property
    def id(self):
        """Gets the id of this EmbeddingDatabase.  # noqa: E501


        :return: The id of this EmbeddingDatabase.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EmbeddingDatabase.


        :param id: The id of this EmbeddingDatabase.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def documents(self):
        """Gets the documents of this EmbeddingDatabase.  # noqa: E501


        :return: The documents of this EmbeddingDatabase.  # noqa: E501
        :rtype: list[Document]
        """
        return self._documents

    @documents.setter
    def documents(self, documents):
        """Sets the documents of this EmbeddingDatabase.


        :param documents: The documents of this EmbeddingDatabase.  # noqa: E501
        :type: list[Document]
        """

        self._documents = documents

    @property
    def api_key(self):
        """Gets the api_key of this EmbeddingDatabase.  # noqa: E501


        :return: The api_key of this EmbeddingDatabase.  # noqa: E501
        :rtype: Credential
        """
        return self._api_key

    @api_key.setter
    def api_key(self, api_key):
        """Sets the api_key of this EmbeddingDatabase.


        :param api_key: The api_key of this EmbeddingDatabase.  # noqa: E501
        :type: Credential
        """

        self._api_key = api_key

    @property
    def api_key_id(self):
        """Gets the api_key_id of this EmbeddingDatabase.  # noqa: E501


        :return: The api_key_id of this EmbeddingDatabase.  # noqa: E501
        :rtype: int
        """
        return self._api_key_id

    @api_key_id.setter
    def api_key_id(self, api_key_id):
        """Sets the api_key_id of this EmbeddingDatabase.


        :param api_key_id: The api_key_id of this EmbeddingDatabase.  # noqa: E501
        :type: int
        """

        self._api_key_id = api_key_id

    @property
    def embedding_api_key(self):
        """Gets the embedding_api_key of this EmbeddingDatabase.  # noqa: E501


        :return: The embedding_api_key of this EmbeddingDatabase.  # noqa: E501
        :rtype: Credential
        """
        return self._embedding_api_key

    @embedding_api_key.setter
    def embedding_api_key(self, embedding_api_key):
        """Sets the embedding_api_key of this EmbeddingDatabase.


        :param embedding_api_key: The embedding_api_key of this EmbeddingDatabase.  # noqa: E501
        :type: Credential
        """

        self._embedding_api_key = embedding_api_key

    @property
    def embedding_api_key_id(self):
        """Gets the embedding_api_key_id of this EmbeddingDatabase.  # noqa: E501


        :return: The embedding_api_key_id of this EmbeddingDatabase.  # noqa: E501
        :rtype: int
        """
        return self._embedding_api_key_id

    @embedding_api_key_id.setter
    def embedding_api_key_id(self, embedding_api_key_id):
        """Sets the embedding_api_key_id of this EmbeddingDatabase.


        :param embedding_api_key_id: The embedding_api_key_id of this EmbeddingDatabase.  # noqa: E501
        :type: int
        """

        self._embedding_api_key_id = embedding_api_key_id

    @property
    def name(self):
        """Gets the name of this EmbeddingDatabase.  # noqa: E501


        :return: The name of this EmbeddingDatabase.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EmbeddingDatabase.


        :param name: The name of this EmbeddingDatabase.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) > 255):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `255`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def provider(self):
        """Gets the provider of this EmbeddingDatabase.  # noqa: E501


        :return: The provider of this EmbeddingDatabase.  # noqa: E501
        :rtype: str
        """
        return self._provider

    @provider.setter
    def provider(self, provider):
        """Sets the provider of this EmbeddingDatabase.


        :param provider: The provider of this EmbeddingDatabase.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and provider is None:  # noqa: E501
            raise ValueError("Invalid value for `provider`, must not be `None`")  # noqa: E501
        allowed_values = ["INTERNAL", "EXTERNAL", "OPENAI", "PINECONE"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and provider not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `provider` ({0}), must be one of {1}"  # noqa: E501
                .format(provider, allowed_values)
            )

        self._provider = provider

    @property
    def index_name(self):
        """Gets the index_name of this EmbeddingDatabase.  # noqa: E501


        :return: The index_name of this EmbeddingDatabase.  # noqa: E501
        :rtype: str
        """
        return self._index_name

    @index_name.setter
    def index_name(self, index_name):
        """Sets the index_name of this EmbeddingDatabase.


        :param index_name: The index_name of this EmbeddingDatabase.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                index_name is not None and len(index_name) > 255):
            raise ValueError("Invalid value for `index_name`, length must be less than or equal to `255`")  # noqa: E501

        self._index_name = index_name

    @property
    def openai_vector_store_id(self):
        """Gets the openai_vector_store_id of this EmbeddingDatabase.  # noqa: E501


        :return: The openai_vector_store_id of this EmbeddingDatabase.  # noqa: E501
        :rtype: str
        """
        return self._openai_vector_store_id

    @openai_vector_store_id.setter
    def openai_vector_store_id(self, openai_vector_store_id):
        """Sets the openai_vector_store_id of this EmbeddingDatabase.


        :param openai_vector_store_id: The openai_vector_store_id of this EmbeddingDatabase.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                openai_vector_store_id is not None and len(openai_vector_store_id) > 100):
            raise ValueError("Invalid value for `openai_vector_store_id`, length must be less than or equal to `100`")  # noqa: E501

        self._openai_vector_store_id = openai_vector_store_id

    @property
    def user(self):
        """Gets the user of this EmbeddingDatabase.  # noqa: E501


        :return: The user of this EmbeddingDatabase.  # noqa: E501
        :rtype: int
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this EmbeddingDatabase.


        :param user: The user of this EmbeddingDatabase.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and user is None:  # noqa: E501
            raise ValueError("Invalid value for `user`, must not be `None`")  # noqa: E501

        self._user = user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EmbeddingDatabase):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EmbeddingDatabase):
            return True

        return self.to_dict() != other.to_dict()
