# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from autoppia_backend_client.configuration import Configuration


class IntegrationAttribute(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'credential_name': 'str',
        'name': 'str',
        'description': 'str',
        'variable_type': 'str',
        'required': 'bool',
        'is_credential': 'bool',
        'credential_type': 'str',
        'editable': 'bool',
        'default_value': 'str',
        'is_document': 'bool',
        'integration': 'int'
    }

    attribute_map = {
        'id': 'id',
        'credential_name': 'credential_name',
        'name': 'name',
        'description': 'description',
        'variable_type': 'variable_type',
        'required': 'required',
        'is_credential': 'is_credential',
        'credential_type': 'credential_type',
        'editable': 'editable',
        'default_value': 'default_value',
        'is_document': 'is_document',
        'integration': 'integration'
    }

    def __init__(self, id=None, credential_name=None, name=None, description=None, variable_type=None, required=None, is_credential=None, credential_type=None, editable=None, default_value=None, is_document=None, integration=None, local_vars_configuration=None):  # noqa: E501
        """IntegrationAttribute - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._credential_name = None
        self._name = None
        self._description = None
        self._variable_type = None
        self._required = None
        self._is_credential = None
        self._credential_type = None
        self._editable = None
        self._default_value = None
        self._is_document = None
        self._integration = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if credential_name is not None:
            self.credential_name = credential_name
        self.name = name
        self.description = description
        self.variable_type = variable_type
        if required is not None:
            self.required = required
        if is_credential is not None:
            self.is_credential = is_credential
        self.credential_type = credential_type
        if editable is not None:
            self.editable = editable
        self.default_value = default_value
        if is_document is not None:
            self.is_document = is_document
        self.integration = integration

    @property
    def id(self):
        """Gets the id of this IntegrationAttribute.  # noqa: E501


        :return: The id of this IntegrationAttribute.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this IntegrationAttribute.


        :param id: The id of this IntegrationAttribute.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def credential_name(self):
        """Gets the credential_name of this IntegrationAttribute.  # noqa: E501


        :return: The credential_name of this IntegrationAttribute.  # noqa: E501
        :rtype: str
        """
        return self._credential_name

    @credential_name.setter
    def credential_name(self, credential_name):
        """Sets the credential_name of this IntegrationAttribute.


        :param credential_name: The credential_name of this IntegrationAttribute.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                credential_name is not None and len(credential_name) < 1):
            raise ValueError("Invalid value for `credential_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._credential_name = credential_name

    @property
    def name(self):
        """Gets the name of this IntegrationAttribute.  # noqa: E501


        :return: The name of this IntegrationAttribute.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this IntegrationAttribute.


        :param name: The name of this IntegrationAttribute.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) > 100):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `100`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this IntegrationAttribute.  # noqa: E501


        :return: The description of this IntegrationAttribute.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this IntegrationAttribute.


        :param description: The description of this IntegrationAttribute.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                description is not None and len(description) > 255):
            raise ValueError("Invalid value for `description`, length must be less than or equal to `255`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                description is not None and len(description) < 1):
            raise ValueError("Invalid value for `description`, length must be greater than or equal to `1`")  # noqa: E501

        self._description = description

    @property
    def variable_type(self):
        """Gets the variable_type of this IntegrationAttribute.  # noqa: E501


        :return: The variable_type of this IntegrationAttribute.  # noqa: E501
        :rtype: str
        """
        return self._variable_type

    @variable_type.setter
    def variable_type(self, variable_type):
        """Sets the variable_type of this IntegrationAttribute.


        :param variable_type: The variable_type of this IntegrationAttribute.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and variable_type is None:  # noqa: E501
            raise ValueError("Invalid value for `variable_type`, must not be `None`")  # noqa: E501
        allowed_values = ["string", "integer", "api_key", "url", "port", "default"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and variable_type not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `variable_type` ({0}), must be one of {1}"  # noqa: E501
                .format(variable_type, allowed_values)
            )

        self._variable_type = variable_type

    @property
    def required(self):
        """Gets the required of this IntegrationAttribute.  # noqa: E501


        :return: The required of this IntegrationAttribute.  # noqa: E501
        :rtype: bool
        """
        return self._required

    @required.setter
    def required(self, required):
        """Sets the required of this IntegrationAttribute.


        :param required: The required of this IntegrationAttribute.  # noqa: E501
        :type: bool
        """

        self._required = required

    @property
    def is_credential(self):
        """Gets the is_credential of this IntegrationAttribute.  # noqa: E501


        :return: The is_credential of this IntegrationAttribute.  # noqa: E501
        :rtype: bool
        """
        return self._is_credential

    @is_credential.setter
    def is_credential(self, is_credential):
        """Sets the is_credential of this IntegrationAttribute.


        :param is_credential: The is_credential of this IntegrationAttribute.  # noqa: E501
        :type: bool
        """

        self._is_credential = is_credential

    @property
    def credential_type(self):
        """Gets the credential_type of this IntegrationAttribute.  # noqa: E501


        :return: The credential_type of this IntegrationAttribute.  # noqa: E501
        :rtype: str
        """
        return self._credential_type

    @credential_type.setter
    def credential_type(self, credential_type):
        """Sets the credential_type of this IntegrationAttribute.


        :param credential_type: The credential_type of this IntegrationAttribute.  # noqa: E501
        :type: str
        """
        allowed_values = [None,"password", "oauth", "apikey", "token"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and credential_type not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `credential_type` ({0}), must be one of {1}"  # noqa: E501
                .format(credential_type, allowed_values)
            )

        self._credential_type = credential_type

    @property
    def editable(self):
        """Gets the editable of this IntegrationAttribute.  # noqa: E501


        :return: The editable of this IntegrationAttribute.  # noqa: E501
        :rtype: bool
        """
        return self._editable

    @editable.setter
    def editable(self, editable):
        """Sets the editable of this IntegrationAttribute.


        :param editable: The editable of this IntegrationAttribute.  # noqa: E501
        :type: bool
        """

        self._editable = editable

    @property
    def default_value(self):
        """Gets the default_value of this IntegrationAttribute.  # noqa: E501


        :return: The default_value of this IntegrationAttribute.  # noqa: E501
        :rtype: str
        """
        return self._default_value

    @default_value.setter
    def default_value(self, default_value):
        """Sets the default_value of this IntegrationAttribute.


        :param default_value: The default_value of this IntegrationAttribute.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                default_value is not None and len(default_value) > 255):
            raise ValueError("Invalid value for `default_value`, length must be less than or equal to `255`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                default_value is not None and len(default_value) < 1):
            raise ValueError("Invalid value for `default_value`, length must be greater than or equal to `1`")  # noqa: E501

        self._default_value = default_value

    @property
    def is_document(self):
        """Gets the is_document of this IntegrationAttribute.  # noqa: E501


        :return: The is_document of this IntegrationAttribute.  # noqa: E501
        :rtype: bool
        """
        return self._is_document

    @is_document.setter
    def is_document(self, is_document):
        """Sets the is_document of this IntegrationAttribute.


        :param is_document: The is_document of this IntegrationAttribute.  # noqa: E501
        :type: bool
        """

        self._is_document = is_document

    @property
    def integration(self):
        """Gets the integration of this IntegrationAttribute.  # noqa: E501


        :return: The integration of this IntegrationAttribute.  # noqa: E501
        :rtype: int
        """
        return self._integration

    @integration.setter
    def integration(self, integration):
        """Sets the integration of this IntegrationAttribute.


        :param integration: The integration of this IntegrationAttribute.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and integration is None:  # noqa: E501
            raise ValueError("Invalid value for `integration`, must not be `None`")  # noqa: E501

        self._integration = integration

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IntegrationAttribute):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IntegrationAttribute):
            return True

        return self.to_dict() != other.to_dict()
