# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from autoppia_backend_client.configuration import Configuration


class ListUserConfigurationAttribute(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'user_configuration': 'int',
        'toolkit_attribute': 'int',
        'toolkit_attribute_obj': 'ListToolkitAttribute',
        'value': 'str'
    }

    attribute_map = {
        'id': 'id',
        'user_configuration': 'user_configuration',
        'toolkit_attribute': 'toolkit_attribute',
        'toolkit_attribute_obj': 'toolkit_attribute_obj',
        'value': 'value'
    }

    def __init__(self, id=None, user_configuration=None, toolkit_attribute=None, toolkit_attribute_obj=None, value=None, local_vars_configuration=None):  # noqa: E501
        """ListUserConfigurationAttribute - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._user_configuration = None
        self._toolkit_attribute = None
        self._toolkit_attribute_obj = None
        self._value = None
        self.discriminator = None

        self.id = id
        self.user_configuration = user_configuration
        self.toolkit_attribute = toolkit_attribute
        self.toolkit_attribute_obj = toolkit_attribute_obj
        self.value = value

    @property
    def id(self):
        """Gets the id of this ListUserConfigurationAttribute.  # noqa: E501


        :return: The id of this ListUserConfigurationAttribute.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ListUserConfigurationAttribute.


        :param id: The id of this ListUserConfigurationAttribute.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def user_configuration(self):
        """Gets the user_configuration of this ListUserConfigurationAttribute.  # noqa: E501


        :return: The user_configuration of this ListUserConfigurationAttribute.  # noqa: E501
        :rtype: int
        """
        return self._user_configuration

    @user_configuration.setter
    def user_configuration(self, user_configuration):
        """Sets the user_configuration of this ListUserConfigurationAttribute.


        :param user_configuration: The user_configuration of this ListUserConfigurationAttribute.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and user_configuration is None:  # noqa: E501
            raise ValueError("Invalid value for `user_configuration`, must not be `None`")  # noqa: E501

        self._user_configuration = user_configuration

    @property
    def toolkit_attribute(self):
        """Gets the toolkit_attribute of this ListUserConfigurationAttribute.  # noqa: E501


        :return: The toolkit_attribute of this ListUserConfigurationAttribute.  # noqa: E501
        :rtype: int
        """
        return self._toolkit_attribute

    @toolkit_attribute.setter
    def toolkit_attribute(self, toolkit_attribute):
        """Sets the toolkit_attribute of this ListUserConfigurationAttribute.


        :param toolkit_attribute: The toolkit_attribute of this ListUserConfigurationAttribute.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and toolkit_attribute is None:  # noqa: E501
            raise ValueError("Invalid value for `toolkit_attribute`, must not be `None`")  # noqa: E501

        self._toolkit_attribute = toolkit_attribute

    @property
    def toolkit_attribute_obj(self):
        """Gets the toolkit_attribute_obj of this ListUserConfigurationAttribute.  # noqa: E501


        :return: The toolkit_attribute_obj of this ListUserConfigurationAttribute.  # noqa: E501
        :rtype: ListToolkitAttribute
        """
        return self._toolkit_attribute_obj

    @toolkit_attribute_obj.setter
    def toolkit_attribute_obj(self, toolkit_attribute_obj):
        """Sets the toolkit_attribute_obj of this ListUserConfigurationAttribute.


        :param toolkit_attribute_obj: The toolkit_attribute_obj of this ListUserConfigurationAttribute.  # noqa: E501
        :type: ListToolkitAttribute
        """
        if self.local_vars_configuration.client_side_validation and toolkit_attribute_obj is None:  # noqa: E501
            raise ValueError("Invalid value for `toolkit_attribute_obj`, must not be `None`")  # noqa: E501

        self._toolkit_attribute_obj = toolkit_attribute_obj

    @property
    def value(self):
        """Gets the value of this ListUserConfigurationAttribute.  # noqa: E501


        :return: The value of this ListUserConfigurationAttribute.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ListUserConfigurationAttribute.


        :param value: The value of this ListUserConfigurationAttribute.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                value is not None and len(value) > 100):
            raise ValueError("Invalid value for `value`, length must be less than or equal to `100`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                value is not None and len(value) < 1):
            raise ValueError("Invalid value for `value`, length must be greater than or equal to `1`")  # noqa: E501

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListUserConfigurationAttribute):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ListUserConfigurationAttribute):
            return True

        return self.to_dict() != other.to_dict()
