# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from autoppia_backend_client.configuration import Configuration


class ListUserConfiguration(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'name': 'str',
        'instruction': 'str',
        'user_toolkit': 'UserToolkitInfo',
        'has_attributes': 'bool',
        'user_configuration_attributes': 'list[ListUserConfigurationAttribute]',
        'has_linked_integrations': 'bool',
        'user_configuration_linked_integrations': 'list[ListUserConfigurationLinkedIntegration]',
        'has_extra_files': 'bool',
        'user_configuration_extra_files': 'list[ListUserConfigurationExtraFile]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'instruction': 'instruction',
        'user_toolkit': 'user_toolkit',
        'has_attributes': 'has_attributes',
        'user_configuration_attributes': 'user_configuration_attributes',
        'has_linked_integrations': 'has_linked_integrations',
        'user_configuration_linked_integrations': 'user_configuration_linked_integrations',
        'has_extra_files': 'has_extra_files',
        'user_configuration_extra_files': 'user_configuration_extra_files'
    }

    def __init__(self, id=None, name=None, instruction=None, user_toolkit=None, has_attributes=None, user_configuration_attributes=None, has_linked_integrations=None, user_configuration_linked_integrations=None, has_extra_files=None, user_configuration_extra_files=None, local_vars_configuration=None):  # noqa: E501
        """ListUserConfiguration - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._instruction = None
        self._user_toolkit = None
        self._has_attributes = None
        self._user_configuration_attributes = None
        self._has_linked_integrations = None
        self._user_configuration_linked_integrations = None
        self._has_extra_files = None
        self._user_configuration_extra_files = None
        self.discriminator = None

        self.id = id
        self.name = name
        if instruction is not None:
            self.instruction = instruction
        self.user_toolkit = user_toolkit
        if has_attributes is not None:
            self.has_attributes = has_attributes
        self.user_configuration_attributes = user_configuration_attributes
        if has_linked_integrations is not None:
            self.has_linked_integrations = has_linked_integrations
        self.user_configuration_linked_integrations = user_configuration_linked_integrations
        if has_extra_files is not None:
            self.has_extra_files = has_extra_files
        self.user_configuration_extra_files = user_configuration_extra_files

    @property
    def id(self):
        """Gets the id of this ListUserConfiguration.  # noqa: E501


        :return: The id of this ListUserConfiguration.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ListUserConfiguration.


        :param id: The id of this ListUserConfiguration.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this ListUserConfiguration.  # noqa: E501


        :return: The name of this ListUserConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ListUserConfiguration.


        :param name: The name of this ListUserConfiguration.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) > 100):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `100`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def instruction(self):
        """Gets the instruction of this ListUserConfiguration.  # noqa: E501


        :return: The instruction of this ListUserConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._instruction

    @instruction.setter
    def instruction(self, instruction):
        """Sets the instruction of this ListUserConfiguration.


        :param instruction: The instruction of this ListUserConfiguration.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                instruction is not None and len(instruction) < 1):
            raise ValueError("Invalid value for `instruction`, length must be greater than or equal to `1`")  # noqa: E501

        self._instruction = instruction

    @property
    def user_toolkit(self):
        """Gets the user_toolkit of this ListUserConfiguration.  # noqa: E501


        :return: The user_toolkit of this ListUserConfiguration.  # noqa: E501
        :rtype: UserToolkitInfo
        """
        return self._user_toolkit

    @user_toolkit.setter
    def user_toolkit(self, user_toolkit):
        """Sets the user_toolkit of this ListUserConfiguration.


        :param user_toolkit: The user_toolkit of this ListUserConfiguration.  # noqa: E501
        :type: UserToolkitInfo
        """
        if self.local_vars_configuration.client_side_validation and user_toolkit is None:  # noqa: E501
            raise ValueError("Invalid value for `user_toolkit`, must not be `None`")  # noqa: E501

        self._user_toolkit = user_toolkit

    @property
    def has_attributes(self):
        """Gets the has_attributes of this ListUserConfiguration.  # noqa: E501


        :return: The has_attributes of this ListUserConfiguration.  # noqa: E501
        :rtype: bool
        """
        return self._has_attributes

    @has_attributes.setter
    def has_attributes(self, has_attributes):
        """Sets the has_attributes of this ListUserConfiguration.


        :param has_attributes: The has_attributes of this ListUserConfiguration.  # noqa: E501
        :type: bool
        """

        self._has_attributes = has_attributes

    @property
    def user_configuration_attributes(self):
        """Gets the user_configuration_attributes of this ListUserConfiguration.  # noqa: E501


        :return: The user_configuration_attributes of this ListUserConfiguration.  # noqa: E501
        :rtype: list[ListUserConfigurationAttribute]
        """
        return self._user_configuration_attributes

    @user_configuration_attributes.setter
    def user_configuration_attributes(self, user_configuration_attributes):
        """Sets the user_configuration_attributes of this ListUserConfiguration.


        :param user_configuration_attributes: The user_configuration_attributes of this ListUserConfiguration.  # noqa: E501
        :type: list[ListUserConfigurationAttribute]
        """
        if self.local_vars_configuration.client_side_validation and user_configuration_attributes is None:  # noqa: E501
            raise ValueError("Invalid value for `user_configuration_attributes`, must not be `None`")  # noqa: E501

        self._user_configuration_attributes = user_configuration_attributes

    @property
    def has_linked_integrations(self):
        """Gets the has_linked_integrations of this ListUserConfiguration.  # noqa: E501


        :return: The has_linked_integrations of this ListUserConfiguration.  # noqa: E501
        :rtype: bool
        """
        return self._has_linked_integrations

    @has_linked_integrations.setter
    def has_linked_integrations(self, has_linked_integrations):
        """Sets the has_linked_integrations of this ListUserConfiguration.


        :param has_linked_integrations: The has_linked_integrations of this ListUserConfiguration.  # noqa: E501
        :type: bool
        """

        self._has_linked_integrations = has_linked_integrations

    @property
    def user_configuration_linked_integrations(self):
        """Gets the user_configuration_linked_integrations of this ListUserConfiguration.  # noqa: E501


        :return: The user_configuration_linked_integrations of this ListUserConfiguration.  # noqa: E501
        :rtype: list[ListUserConfigurationLinkedIntegration]
        """
        return self._user_configuration_linked_integrations

    @user_configuration_linked_integrations.setter
    def user_configuration_linked_integrations(self, user_configuration_linked_integrations):
        """Sets the user_configuration_linked_integrations of this ListUserConfiguration.


        :param user_configuration_linked_integrations: The user_configuration_linked_integrations of this ListUserConfiguration.  # noqa: E501
        :type: list[ListUserConfigurationLinkedIntegration]
        """
        if self.local_vars_configuration.client_side_validation and user_configuration_linked_integrations is None:  # noqa: E501
            raise ValueError("Invalid value for `user_configuration_linked_integrations`, must not be `None`")  # noqa: E501

        self._user_configuration_linked_integrations = user_configuration_linked_integrations

    @property
    def has_extra_files(self):
        """Gets the has_extra_files of this ListUserConfiguration.  # noqa: E501


        :return: The has_extra_files of this ListUserConfiguration.  # noqa: E501
        :rtype: bool
        """
        return self._has_extra_files

    @has_extra_files.setter
    def has_extra_files(self, has_extra_files):
        """Sets the has_extra_files of this ListUserConfiguration.


        :param has_extra_files: The has_extra_files of this ListUserConfiguration.  # noqa: E501
        :type: bool
        """

        self._has_extra_files = has_extra_files

    @property
    def user_configuration_extra_files(self):
        """Gets the user_configuration_extra_files of this ListUserConfiguration.  # noqa: E501


        :return: The user_configuration_extra_files of this ListUserConfiguration.  # noqa: E501
        :rtype: list[ListUserConfigurationExtraFile]
        """
        return self._user_configuration_extra_files

    @user_configuration_extra_files.setter
    def user_configuration_extra_files(self, user_configuration_extra_files):
        """Sets the user_configuration_extra_files of this ListUserConfiguration.


        :param user_configuration_extra_files: The user_configuration_extra_files of this ListUserConfiguration.  # noqa: E501
        :type: list[ListUserConfigurationExtraFile]
        """
        if self.local_vars_configuration.client_side_validation and user_configuration_extra_files is None:  # noqa: E501
            raise ValueError("Invalid value for `user_configuration_extra_files`, must not be `None`")  # noqa: E501

        self._user_configuration_extra_files = user_configuration_extra_files

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListUserConfiguration):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ListUserConfiguration):
            return True

        return self.to_dict() != other.to_dict()
