# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from autoppia_backend_client.configuration import Configuration


class ListToolkitAttribute(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'toolkit': 'int',
        'name': 'str',
        'description': 'str',
        'variable_type': 'str',
        'required': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'toolkit': 'toolkit',
        'name': 'name',
        'description': 'description',
        'variable_type': 'variable_type',
        'required': 'required'
    }

    def __init__(self, id=None, toolkit=None, name=None, description=None, variable_type=None, required=None, local_vars_configuration=None):  # noqa: E501
        """ListToolkitAttribute - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._toolkit = None
        self._name = None
        self._description = None
        self._variable_type = None
        self._required = None
        self.discriminator = None

        self.id = id
        self.toolkit = toolkit
        self.name = name
        if description is not None:
            self.description = description
        self.variable_type = variable_type
        self.required = required

    @property
    def id(self):
        """Gets the id of this ListToolkitAttribute.  # noqa: E501


        :return: The id of this ListToolkitAttribute.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ListToolkitAttribute.


        :param id: The id of this ListToolkitAttribute.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def toolkit(self):
        """Gets the toolkit of this ListToolkitAttribute.  # noqa: E501


        :return: The toolkit of this ListToolkitAttribute.  # noqa: E501
        :rtype: int
        """
        return self._toolkit

    @toolkit.setter
    def toolkit(self, toolkit):
        """Sets the toolkit of this ListToolkitAttribute.


        :param toolkit: The toolkit of this ListToolkitAttribute.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and toolkit is None:  # noqa: E501
            raise ValueError("Invalid value for `toolkit`, must not be `None`")  # noqa: E501

        self._toolkit = toolkit

    @property
    def name(self):
        """Gets the name of this ListToolkitAttribute.  # noqa: E501


        :return: The name of this ListToolkitAttribute.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ListToolkitAttribute.


        :param name: The name of this ListToolkitAttribute.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) > 100):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `100`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this ListToolkitAttribute.  # noqa: E501


        :return: The description of this ListToolkitAttribute.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ListToolkitAttribute.


        :param description: The description of this ListToolkitAttribute.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                description is not None and len(description) > 255):
            raise ValueError("Invalid value for `description`, length must be less than or equal to `255`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                description is not None and len(description) < 1):
            raise ValueError("Invalid value for `description`, length must be greater than or equal to `1`")  # noqa: E501

        self._description = description

    @property
    def variable_type(self):
        """Gets the variable_type of this ListToolkitAttribute.  # noqa: E501


        :return: The variable_type of this ListToolkitAttribute.  # noqa: E501
        :rtype: str
        """
        return self._variable_type

    @variable_type.setter
    def variable_type(self, variable_type):
        """Sets the variable_type of this ListToolkitAttribute.


        :param variable_type: The variable_type of this ListToolkitAttribute.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and variable_type is None:  # noqa: E501
            raise ValueError("Invalid value for `variable_type`, must not be `None`")  # noqa: E501
        allowed_values = ["string", "integer", "api_key", "url", "port", "default"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and variable_type not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `variable_type` ({0}), must be one of {1}"  # noqa: E501
                .format(variable_type, allowed_values)
            )

        self._variable_type = variable_type

    @property
    def required(self):
        """Gets the required of this ListToolkitAttribute.  # noqa: E501


        :return: The required of this ListToolkitAttribute.  # noqa: E501
        :rtype: bool
        """
        return self._required

    @required.setter
    def required(self, required):
        """Sets the required of this ListToolkitAttribute.


        :param required: The required of this ListToolkitAttribute.  # noqa: E501
        :type: bool
        """
        if self.local_vars_configuration.client_side_validation and required is None:  # noqa: E501
            raise ValueError("Invalid value for `required`, must not be `None`")  # noqa: E501

        self._required = required

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListToolkitAttribute):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ListToolkitAttribute):
            return True

        return self.to_dict() != other.to_dict()
