# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from autoppia_backend_client.configuration import Configuration


class Run(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'run_id': 'str',
        'workspace_id': 'int',
        'session_id': 'str',
        'input_content': 'str',
        'output_content': 'str',
        'status': 'str',
        'error': 'str',
        'started_at': 'datetime',
        'ended_at': 'datetime',
        'duration_ms': 'int',
        'total_tokens': 'int',
        'total_llm_calls': 'int',
        'total_tool_calls': 'int',
        'total_delegations': 'int',
        'metadata': 'object',
        'spans': 'list[Span]',
        'workers_involved': 'str'
    }

    attribute_map = {
        'run_id': 'run_id',
        'workspace_id': 'workspace_id',
        'session_id': 'session_id',
        'input_content': 'input_content',
        'output_content': 'output_content',
        'status': 'status',
        'error': 'error',
        'started_at': 'started_at',
        'ended_at': 'ended_at',
        'duration_ms': 'duration_ms',
        'total_tokens': 'total_tokens',
        'total_llm_calls': 'total_llm_calls',
        'total_tool_calls': 'total_tool_calls',
        'total_delegations': 'total_delegations',
        'metadata': 'metadata',
        'spans': 'spans',
        'workers_involved': 'workers_involved'
    }

    def __init__(self, run_id=None, workspace_id=None, session_id=None, input_content=None, output_content=None, status=None, error=None, started_at=None, ended_at=None, duration_ms=None, total_tokens=None, total_llm_calls=None, total_tool_calls=None, total_delegations=None, metadata=None, spans=None, workers_involved=None, local_vars_configuration=None):  # noqa: E501
        """Run - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._run_id = None
        self._workspace_id = None
        self._session_id = None
        self._input_content = None
        self._output_content = None
        self._status = None
        self._error = None
        self._started_at = None
        self._ended_at = None
        self._duration_ms = None
        self._total_tokens = None
        self._total_llm_calls = None
        self._total_tool_calls = None
        self._total_delegations = None
        self._metadata = None
        self._spans = None
        self._workers_involved = None
        self.discriminator = None

        self.run_id = run_id
        if workspace_id is not None:
            self.workspace_id = workspace_id
        self.session_id = session_id
        self.input_content = input_content
        self.output_content = output_content
        if status is not None:
            self.status = status
        self.error = error
        if started_at is not None:
            self.started_at = started_at
        self.ended_at = ended_at
        self.duration_ms = duration_ms
        if total_tokens is not None:
            self.total_tokens = total_tokens
        if total_llm_calls is not None:
            self.total_llm_calls = total_llm_calls
        if total_tool_calls is not None:
            self.total_tool_calls = total_tool_calls
        if total_delegations is not None:
            self.total_delegations = total_delegations
        if metadata is not None:
            self.metadata = metadata
        if spans is not None:
            self.spans = spans
        if workers_involved is not None:
            self.workers_involved = workers_involved

    @property
    def run_id(self):
        """Gets the run_id of this Run.  # noqa: E501


        :return: The run_id of this Run.  # noqa: E501
        :rtype: str
        """
        return self._run_id

    @run_id.setter
    def run_id(self, run_id):
        """Sets the run_id of this Run.


        :param run_id: The run_id of this Run.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and run_id is None:  # noqa: E501
            raise ValueError("Invalid value for `run_id`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                run_id is not None and len(run_id) > 50):
            raise ValueError("Invalid value for `run_id`, length must be less than or equal to `50`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                run_id is not None and len(run_id) < 1):
            raise ValueError("Invalid value for `run_id`, length must be greater than or equal to `1`")  # noqa: E501

        self._run_id = run_id

    @property
    def workspace_id(self):
        """Gets the workspace_id of this Run.  # noqa: E501


        :return: The workspace_id of this Run.  # noqa: E501
        :rtype: int
        """
        return self._workspace_id

    @workspace_id.setter
    def workspace_id(self, workspace_id):
        """Sets the workspace_id of this Run.


        :param workspace_id: The workspace_id of this Run.  # noqa: E501
        :type: int
        """

        self._workspace_id = workspace_id

    @property
    def session_id(self):
        """Gets the session_id of this Run.  # noqa: E501


        :return: The session_id of this Run.  # noqa: E501
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id):
        """Sets the session_id of this Run.


        :param session_id: The session_id of this Run.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                session_id is not None and len(session_id) > 100):
            raise ValueError("Invalid value for `session_id`, length must be less than or equal to `100`")  # noqa: E501

        self._session_id = session_id

    @property
    def input_content(self):
        """Gets the input_content of this Run.  # noqa: E501


        :return: The input_content of this Run.  # noqa: E501
        :rtype: str
        """
        return self._input_content

    @input_content.setter
    def input_content(self, input_content):
        """Sets the input_content of this Run.


        :param input_content: The input_content of this Run.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and input_content is None:  # noqa: E501
            raise ValueError("Invalid value for `input_content`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                input_content is not None and len(input_content) < 1):
            raise ValueError("Invalid value for `input_content`, length must be greater than or equal to `1`")  # noqa: E501

        self._input_content = input_content

    @property
    def output_content(self):
        """Gets the output_content of this Run.  # noqa: E501


        :return: The output_content of this Run.  # noqa: E501
        :rtype: str
        """
        return self._output_content

    @output_content.setter
    def output_content(self, output_content):
        """Sets the output_content of this Run.


        :param output_content: The output_content of this Run.  # noqa: E501
        :type: str
        """

        self._output_content = output_content

    @property
    def status(self):
        """Gets the status of this Run.  # noqa: E501


        :return: The status of this Run.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Run.


        :param status: The status of this Run.  # noqa: E501
        :type: str
        """
        allowed_values = ["running", "completed", "failed"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and status not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def error(self):
        """Gets the error of this Run.  # noqa: E501


        :return: The error of this Run.  # noqa: E501
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this Run.


        :param error: The error of this Run.  # noqa: E501
        :type: str
        """

        self._error = error

    @property
    def started_at(self):
        """Gets the started_at of this Run.  # noqa: E501


        :return: The started_at of this Run.  # noqa: E501
        :rtype: datetime
        """
        return self._started_at

    @started_at.setter
    def started_at(self, started_at):
        """Sets the started_at of this Run.


        :param started_at: The started_at of this Run.  # noqa: E501
        :type: datetime
        """

        self._started_at = started_at

    @property
    def ended_at(self):
        """Gets the ended_at of this Run.  # noqa: E501


        :return: The ended_at of this Run.  # noqa: E501
        :rtype: datetime
        """
        return self._ended_at

    @ended_at.setter
    def ended_at(self, ended_at):
        """Sets the ended_at of this Run.


        :param ended_at: The ended_at of this Run.  # noqa: E501
        :type: datetime
        """

        self._ended_at = ended_at

    @property
    def duration_ms(self):
        """Gets the duration_ms of this Run.  # noqa: E501


        :return: The duration_ms of this Run.  # noqa: E501
        :rtype: int
        """
        return self._duration_ms

    @duration_ms.setter
    def duration_ms(self, duration_ms):
        """Sets the duration_ms of this Run.


        :param duration_ms: The duration_ms of this Run.  # noqa: E501
        :type: int
        """
        if (self.local_vars_configuration.client_side_validation and
                duration_ms is not None and duration_ms > 9223372036854775807):  # noqa: E501
            raise ValueError("Invalid value for `duration_ms`, must be a value less than or equal to `9223372036854775807`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                duration_ms is not None and duration_ms < -9223372036854775808):  # noqa: E501
            raise ValueError("Invalid value for `duration_ms`, must be a value greater than or equal to `-9223372036854775808`")  # noqa: E501

        self._duration_ms = duration_ms

    @property
    def total_tokens(self):
        """Gets the total_tokens of this Run.  # noqa: E501


        :return: The total_tokens of this Run.  # noqa: E501
        :rtype: int
        """
        return self._total_tokens

    @total_tokens.setter
    def total_tokens(self, total_tokens):
        """Sets the total_tokens of this Run.


        :param total_tokens: The total_tokens of this Run.  # noqa: E501
        :type: int
        """
        if (self.local_vars_configuration.client_side_validation and
                total_tokens is not None and total_tokens > 9223372036854775807):  # noqa: E501
            raise ValueError("Invalid value for `total_tokens`, must be a value less than or equal to `9223372036854775807`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                total_tokens is not None and total_tokens < -9223372036854775808):  # noqa: E501
            raise ValueError("Invalid value for `total_tokens`, must be a value greater than or equal to `-9223372036854775808`")  # noqa: E501

        self._total_tokens = total_tokens

    @property
    def total_llm_calls(self):
        """Gets the total_llm_calls of this Run.  # noqa: E501


        :return: The total_llm_calls of this Run.  # noqa: E501
        :rtype: int
        """
        return self._total_llm_calls

    @total_llm_calls.setter
    def total_llm_calls(self, total_llm_calls):
        """Sets the total_llm_calls of this Run.


        :param total_llm_calls: The total_llm_calls of this Run.  # noqa: E501
        :type: int
        """
        if (self.local_vars_configuration.client_side_validation and
                total_llm_calls is not None and total_llm_calls > 9223372036854775807):  # noqa: E501
            raise ValueError("Invalid value for `total_llm_calls`, must be a value less than or equal to `9223372036854775807`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                total_llm_calls is not None and total_llm_calls < -9223372036854775808):  # noqa: E501
            raise ValueError("Invalid value for `total_llm_calls`, must be a value greater than or equal to `-9223372036854775808`")  # noqa: E501

        self._total_llm_calls = total_llm_calls

    @property
    def total_tool_calls(self):
        """Gets the total_tool_calls of this Run.  # noqa: E501


        :return: The total_tool_calls of this Run.  # noqa: E501
        :rtype: int
        """
        return self._total_tool_calls

    @total_tool_calls.setter
    def total_tool_calls(self, total_tool_calls):
        """Sets the total_tool_calls of this Run.


        :param total_tool_calls: The total_tool_calls of this Run.  # noqa: E501
        :type: int
        """
        if (self.local_vars_configuration.client_side_validation and
                total_tool_calls is not None and total_tool_calls > 9223372036854775807):  # noqa: E501
            raise ValueError("Invalid value for `total_tool_calls`, must be a value less than or equal to `9223372036854775807`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                total_tool_calls is not None and total_tool_calls < -9223372036854775808):  # noqa: E501
            raise ValueError("Invalid value for `total_tool_calls`, must be a value greater than or equal to `-9223372036854775808`")  # noqa: E501

        self._total_tool_calls = total_tool_calls

    @property
    def total_delegations(self):
        """Gets the total_delegations of this Run.  # noqa: E501


        :return: The total_delegations of this Run.  # noqa: E501
        :rtype: int
        """
        return self._total_delegations

    @total_delegations.setter
    def total_delegations(self, total_delegations):
        """Sets the total_delegations of this Run.


        :param total_delegations: The total_delegations of this Run.  # noqa: E501
        :type: int
        """
        if (self.local_vars_configuration.client_side_validation and
                total_delegations is not None and total_delegations > 9223372036854775807):  # noqa: E501
            raise ValueError("Invalid value for `total_delegations`, must be a value less than or equal to `9223372036854775807`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                total_delegations is not None and total_delegations < -9223372036854775808):  # noqa: E501
            raise ValueError("Invalid value for `total_delegations`, must be a value greater than or equal to `-9223372036854775808`")  # noqa: E501

        self._total_delegations = total_delegations

    @property
    def metadata(self):
        """Gets the metadata of this Run.  # noqa: E501


        :return: The metadata of this Run.  # noqa: E501
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this Run.


        :param metadata: The metadata of this Run.  # noqa: E501
        :type: object
        """

        self._metadata = metadata

    @property
    def spans(self):
        """Gets the spans of this Run.  # noqa: E501


        :return: The spans of this Run.  # noqa: E501
        :rtype: list[Span]
        """
        return self._spans

    @spans.setter
    def spans(self, spans):
        """Sets the spans of this Run.


        :param spans: The spans of this Run.  # noqa: E501
        :type: list[Span]
        """

        self._spans = spans

    @property
    def workers_involved(self):
        """Gets the workers_involved of this Run.  # noqa: E501


        :return: The workers_involved of this Run.  # noqa: E501
        :rtype: str
        """
        return self._workers_involved

    @workers_involved.setter
    def workers_involved(self, workers_involved):
        """Sets the workers_involved of this Run.


        :param workers_involved: The workers_involved of this Run.  # noqa: E501
        :type: str
        """

        self._workers_involved = workers_involved

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Run):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Run):
            return True

        return self.to_dict() != other.to_dict()
