# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from autoppia_backend_client.configuration import Configuration


class Span(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'span_id': 'str',
        'worker_ref_id': 'str',
        'worker_name': 'str',
        'parent_span_id': 'str',
        'input_content': 'str',
        'output_content': 'str',
        'status': 'str',
        'error': 'str',
        'started_at': 'datetime',
        'ended_at': 'datetime',
        'duration_ms': 'int',
        'total_tokens': 'int',
        'llm_calls': 'int',
        'tool_calls': 'int',
        'delegations': 'int',
        'events': 'list[SpanEvent]'
    }

    attribute_map = {
        'span_id': 'span_id',
        'worker_ref_id': 'worker_ref_id',
        'worker_name': 'worker_name',
        'parent_span_id': 'parent_span_id',
        'input_content': 'input_content',
        'output_content': 'output_content',
        'status': 'status',
        'error': 'error',
        'started_at': 'started_at',
        'ended_at': 'ended_at',
        'duration_ms': 'duration_ms',
        'total_tokens': 'total_tokens',
        'llm_calls': 'llm_calls',
        'tool_calls': 'tool_calls',
        'delegations': 'delegations',
        'events': 'events'
    }

    def __init__(self, span_id=None, worker_ref_id=None, worker_name=None, parent_span_id=None, input_content=None, output_content=None, status=None, error=None, started_at=None, ended_at=None, duration_ms=None, total_tokens=None, llm_calls=None, tool_calls=None, delegations=None, events=None, local_vars_configuration=None):  # noqa: E501
        """Span - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._span_id = None
        self._worker_ref_id = None
        self._worker_name = None
        self._parent_span_id = None
        self._input_content = None
        self._output_content = None
        self._status = None
        self._error = None
        self._started_at = None
        self._ended_at = None
        self._duration_ms = None
        self._total_tokens = None
        self._llm_calls = None
        self._tool_calls = None
        self._delegations = None
        self._events = None
        self.discriminator = None

        self.span_id = span_id
        self.worker_ref_id = worker_ref_id
        self.worker_name = worker_name
        self.parent_span_id = parent_span_id
        self.input_content = input_content
        self.output_content = output_content
        if status is not None:
            self.status = status
        self.error = error
        if started_at is not None:
            self.started_at = started_at
        self.ended_at = ended_at
        self.duration_ms = duration_ms
        if total_tokens is not None:
            self.total_tokens = total_tokens
        if llm_calls is not None:
            self.llm_calls = llm_calls
        if tool_calls is not None:
            self.tool_calls = tool_calls
        if delegations is not None:
            self.delegations = delegations
        if events is not None:
            self.events = events

    @property
    def span_id(self):
        """Gets the span_id of this Span.  # noqa: E501


        :return: The span_id of this Span.  # noqa: E501
        :rtype: str
        """
        return self._span_id

    @span_id.setter
    def span_id(self, span_id):
        """Sets the span_id of this Span.


        :param span_id: The span_id of this Span.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and span_id is None:  # noqa: E501
            raise ValueError("Invalid value for `span_id`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                span_id is not None and len(span_id) > 50):
            raise ValueError("Invalid value for `span_id`, length must be less than or equal to `50`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                span_id is not None and len(span_id) < 1):
            raise ValueError("Invalid value for `span_id`, length must be greater than or equal to `1`")  # noqa: E501

        self._span_id = span_id

    @property
    def worker_ref_id(self):
        """Gets the worker_ref_id of this Span.  # noqa: E501


        :return: The worker_ref_id of this Span.  # noqa: E501
        :rtype: str
        """
        return self._worker_ref_id

    @worker_ref_id.setter
    def worker_ref_id(self, worker_ref_id):
        """Sets the worker_ref_id of this Span.


        :param worker_ref_id: The worker_ref_id of this Span.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and worker_ref_id is None:  # noqa: E501
            raise ValueError("Invalid value for `worker_ref_id`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                worker_ref_id is not None and len(worker_ref_id) > 100):
            raise ValueError("Invalid value for `worker_ref_id`, length must be less than or equal to `100`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                worker_ref_id is not None and len(worker_ref_id) < 1):
            raise ValueError("Invalid value for `worker_ref_id`, length must be greater than or equal to `1`")  # noqa: E501

        self._worker_ref_id = worker_ref_id

    @property
    def worker_name(self):
        """Gets the worker_name of this Span.  # noqa: E501


        :return: The worker_name of this Span.  # noqa: E501
        :rtype: str
        """
        return self._worker_name

    @worker_name.setter
    def worker_name(self, worker_name):
        """Sets the worker_name of this Span.


        :param worker_name: The worker_name of this Span.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and worker_name is None:  # noqa: E501
            raise ValueError("Invalid value for `worker_name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                worker_name is not None and len(worker_name) > 255):
            raise ValueError("Invalid value for `worker_name`, length must be less than or equal to `255`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                worker_name is not None and len(worker_name) < 1):
            raise ValueError("Invalid value for `worker_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._worker_name = worker_name

    @property
    def parent_span_id(self):
        """Gets the parent_span_id of this Span.  # noqa: E501


        :return: The parent_span_id of this Span.  # noqa: E501
        :rtype: str
        """
        return self._parent_span_id

    @parent_span_id.setter
    def parent_span_id(self, parent_span_id):
        """Sets the parent_span_id of this Span.


        :param parent_span_id: The parent_span_id of this Span.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                parent_span_id is not None and len(parent_span_id) < 1):
            raise ValueError("Invalid value for `parent_span_id`, length must be greater than or equal to `1`")  # noqa: E501

        self._parent_span_id = parent_span_id

    @property
    def input_content(self):
        """Gets the input_content of this Span.  # noqa: E501


        :return: The input_content of this Span.  # noqa: E501
        :rtype: str
        """
        return self._input_content

    @input_content.setter
    def input_content(self, input_content):
        """Sets the input_content of this Span.


        :param input_content: The input_content of this Span.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and input_content is None:  # noqa: E501
            raise ValueError("Invalid value for `input_content`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                input_content is not None and len(input_content) < 1):
            raise ValueError("Invalid value for `input_content`, length must be greater than or equal to `1`")  # noqa: E501

        self._input_content = input_content

    @property
    def output_content(self):
        """Gets the output_content of this Span.  # noqa: E501


        :return: The output_content of this Span.  # noqa: E501
        :rtype: str
        """
        return self._output_content

    @output_content.setter
    def output_content(self, output_content):
        """Sets the output_content of this Span.


        :param output_content: The output_content of this Span.  # noqa: E501
        :type: str
        """

        self._output_content = output_content

    @property
    def status(self):
        """Gets the status of this Span.  # noqa: E501


        :return: The status of this Span.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Span.


        :param status: The status of this Span.  # noqa: E501
        :type: str
        """
        allowed_values = ["running", "completed", "failed"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and status not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def error(self):
        """Gets the error of this Span.  # noqa: E501


        :return: The error of this Span.  # noqa: E501
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this Span.


        :param error: The error of this Span.  # noqa: E501
        :type: str
        """

        self._error = error

    @property
    def started_at(self):
        """Gets the started_at of this Span.  # noqa: E501


        :return: The started_at of this Span.  # noqa: E501
        :rtype: datetime
        """
        return self._started_at

    @started_at.setter
    def started_at(self, started_at):
        """Sets the started_at of this Span.


        :param started_at: The started_at of this Span.  # noqa: E501
        :type: datetime
        """

        self._started_at = started_at

    @property
    def ended_at(self):
        """Gets the ended_at of this Span.  # noqa: E501


        :return: The ended_at of this Span.  # noqa: E501
        :rtype: datetime
        """
        return self._ended_at

    @ended_at.setter
    def ended_at(self, ended_at):
        """Sets the ended_at of this Span.


        :param ended_at: The ended_at of this Span.  # noqa: E501
        :type: datetime
        """

        self._ended_at = ended_at

    @property
    def duration_ms(self):
        """Gets the duration_ms of this Span.  # noqa: E501


        :return: The duration_ms of this Span.  # noqa: E501
        :rtype: int
        """
        return self._duration_ms

    @duration_ms.setter
    def duration_ms(self, duration_ms):
        """Sets the duration_ms of this Span.


        :param duration_ms: The duration_ms of this Span.  # noqa: E501
        :type: int
        """
        if (self.local_vars_configuration.client_side_validation and
                duration_ms is not None and duration_ms > 9223372036854775807):  # noqa: E501
            raise ValueError("Invalid value for `duration_ms`, must be a value less than or equal to `9223372036854775807`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                duration_ms is not None and duration_ms < -9223372036854775808):  # noqa: E501
            raise ValueError("Invalid value for `duration_ms`, must be a value greater than or equal to `-9223372036854775808`")  # noqa: E501

        self._duration_ms = duration_ms

    @property
    def total_tokens(self):
        """Gets the total_tokens of this Span.  # noqa: E501


        :return: The total_tokens of this Span.  # noqa: E501
        :rtype: int
        """
        return self._total_tokens

    @total_tokens.setter
    def total_tokens(self, total_tokens):
        """Sets the total_tokens of this Span.


        :param total_tokens: The total_tokens of this Span.  # noqa: E501
        :type: int
        """
        if (self.local_vars_configuration.client_side_validation and
                total_tokens is not None and total_tokens > 9223372036854775807):  # noqa: E501
            raise ValueError("Invalid value for `total_tokens`, must be a value less than or equal to `9223372036854775807`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                total_tokens is not None and total_tokens < -9223372036854775808):  # noqa: E501
            raise ValueError("Invalid value for `total_tokens`, must be a value greater than or equal to `-9223372036854775808`")  # noqa: E501

        self._total_tokens = total_tokens

    @property
    def llm_calls(self):
        """Gets the llm_calls of this Span.  # noqa: E501


        :return: The llm_calls of this Span.  # noqa: E501
        :rtype: int
        """
        return self._llm_calls

    @llm_calls.setter
    def llm_calls(self, llm_calls):
        """Sets the llm_calls of this Span.


        :param llm_calls: The llm_calls of this Span.  # noqa: E501
        :type: int
        """
        if (self.local_vars_configuration.client_side_validation and
                llm_calls is not None and llm_calls > 9223372036854775807):  # noqa: E501
            raise ValueError("Invalid value for `llm_calls`, must be a value less than or equal to `9223372036854775807`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                llm_calls is not None and llm_calls < -9223372036854775808):  # noqa: E501
            raise ValueError("Invalid value for `llm_calls`, must be a value greater than or equal to `-9223372036854775808`")  # noqa: E501

        self._llm_calls = llm_calls

    @property
    def tool_calls(self):
        """Gets the tool_calls of this Span.  # noqa: E501


        :return: The tool_calls of this Span.  # noqa: E501
        :rtype: int
        """
        return self._tool_calls

    @tool_calls.setter
    def tool_calls(self, tool_calls):
        """Sets the tool_calls of this Span.


        :param tool_calls: The tool_calls of this Span.  # noqa: E501
        :type: int
        """
        if (self.local_vars_configuration.client_side_validation and
                tool_calls is not None and tool_calls > 9223372036854775807):  # noqa: E501
            raise ValueError("Invalid value for `tool_calls`, must be a value less than or equal to `9223372036854775807`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                tool_calls is not None and tool_calls < -9223372036854775808):  # noqa: E501
            raise ValueError("Invalid value for `tool_calls`, must be a value greater than or equal to `-9223372036854775808`")  # noqa: E501

        self._tool_calls = tool_calls

    @property
    def delegations(self):
        """Gets the delegations of this Span.  # noqa: E501


        :return: The delegations of this Span.  # noqa: E501
        :rtype: int
        """
        return self._delegations

    @delegations.setter
    def delegations(self, delegations):
        """Sets the delegations of this Span.


        :param delegations: The delegations of this Span.  # noqa: E501
        :type: int
        """
        if (self.local_vars_configuration.client_side_validation and
                delegations is not None and delegations > 9223372036854775807):  # noqa: E501
            raise ValueError("Invalid value for `delegations`, must be a value less than or equal to `9223372036854775807`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                delegations is not None and delegations < -9223372036854775808):  # noqa: E501
            raise ValueError("Invalid value for `delegations`, must be a value greater than or equal to `-9223372036854775808`")  # noqa: E501

        self._delegations = delegations

    @property
    def events(self):
        """Gets the events of this Span.  # noqa: E501


        :return: The events of this Span.  # noqa: E501
        :rtype: list[SpanEvent]
        """
        return self._events

    @events.setter
    def events(self, events):
        """Sets the events of this Span.


        :param events: The events of this Span.  # noqa: E501
        :type: list[SpanEvent]
        """

        self._events = events

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Span):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Span):
            return True

        return self.to_dict() != other.to_dict()
