# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from autoppia_backend_client.configuration import Configuration


class Test(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'task': 'list[Task]',
        'category': 'list[Category]',
        'category_ids': 'list[int]',
        'worker': 'Worker',
        'worker_id': 'int',
        'results': 'list[Result]',
        'name': 'str',
        'evaluation': 'str',
        'state': 'str',
        'execution_time': 'str',
        'created_date': 'datetime',
        'updated_date': 'datetime',
        'user': 'int'
    }

    attribute_map = {
        'id': 'id',
        'task': 'task',
        'category': 'category',
        'category_ids': 'category_ids',
        'worker': 'worker',
        'worker_id': 'worker_id',
        'results': 'results',
        'name': 'name',
        'evaluation': 'evaluation',
        'state': 'state',
        'execution_time': 'execution_time',
        'created_date': 'created_date',
        'updated_date': 'updated_date',
        'user': 'user'
    }

    def __init__(self, id=None, task=None, category=None, category_ids=None, worker=None, worker_id=None, results=None, name=None, evaluation=None, state=None, execution_time=None, created_date=None, updated_date=None, user=None, local_vars_configuration=None):  # noqa: E501
        """Test - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._task = None
        self._category = None
        self._category_ids = None
        self._worker = None
        self._worker_id = None
        self._results = None
        self._name = None
        self._evaluation = None
        self._state = None
        self._execution_time = None
        self._created_date = None
        self._updated_date = None
        self._user = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if task is not None:
            self.task = task
        if category is not None:
            self.category = category
        if category_ids is not None:
            self.category_ids = category_ids
        if worker is not None:
            self.worker = worker
        if worker_id is not None:
            self.worker_id = worker_id
        if results is not None:
            self.results = results
        self.name = name
        self.evaluation = evaluation
        self.state = state
        self.execution_time = execution_time
        if created_date is not None:
            self.created_date = created_date
        if updated_date is not None:
            self.updated_date = updated_date
        self.user = user

    @property
    def id(self):
        """Gets the id of this Test.  # noqa: E501


        :return: The id of this Test.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Test.


        :param id: The id of this Test.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def task(self):
        """Gets the task of this Test.  # noqa: E501


        :return: The task of this Test.  # noqa: E501
        :rtype: list[Task]
        """
        return self._task

    @task.setter
    def task(self, task):
        """Sets the task of this Test.


        :param task: The task of this Test.  # noqa: E501
        :type: list[Task]
        """

        self._task = task

    @property
    def category(self):
        """Gets the category of this Test.  # noqa: E501


        :return: The category of this Test.  # noqa: E501
        :rtype: list[Category]
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this Test.


        :param category: The category of this Test.  # noqa: E501
        :type: list[Category]
        """

        self._category = category

    @property
    def category_ids(self):
        """Gets the category_ids of this Test.  # noqa: E501


        :return: The category_ids of this Test.  # noqa: E501
        :rtype: list[int]
        """
        return self._category_ids

    @category_ids.setter
    def category_ids(self, category_ids):
        """Sets the category_ids of this Test.


        :param category_ids: The category_ids of this Test.  # noqa: E501
        :type: list[int]
        """

        self._category_ids = category_ids

    @property
    def worker(self):
        """Gets the worker of this Test.  # noqa: E501


        :return: The worker of this Test.  # noqa: E501
        :rtype: Worker
        """
        return self._worker

    @worker.setter
    def worker(self, worker):
        """Sets the worker of this Test.


        :param worker: The worker of this Test.  # noqa: E501
        :type: Worker
        """

        self._worker = worker

    @property
    def worker_id(self):
        """Gets the worker_id of this Test.  # noqa: E501


        :return: The worker_id of this Test.  # noqa: E501
        :rtype: int
        """
        return self._worker_id

    @worker_id.setter
    def worker_id(self, worker_id):
        """Sets the worker_id of this Test.


        :param worker_id: The worker_id of this Test.  # noqa: E501
        :type: int
        """

        self._worker_id = worker_id

    @property
    def results(self):
        """Gets the results of this Test.  # noqa: E501


        :return: The results of this Test.  # noqa: E501
        :rtype: list[Result]
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this Test.


        :param results: The results of this Test.  # noqa: E501
        :type: list[Result]
        """

        self._results = results

    @property
    def name(self):
        """Gets the name of this Test.  # noqa: E501


        :return: The name of this Test.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Test.


        :param name: The name of this Test.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) > 25):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `25`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def evaluation(self):
        """Gets the evaluation of this Test.  # noqa: E501


        :return: The evaluation of this Test.  # noqa: E501
        :rtype: str
        """
        return self._evaluation

    @evaluation.setter
    def evaluation(self, evaluation):
        """Sets the evaluation of this Test.


        :param evaluation: The evaluation of this Test.  # noqa: E501
        :type: str
        """
        allowed_values = [None,"llm", "result contains string", "exact match"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and evaluation not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `evaluation` ({0}), must be one of {1}"  # noqa: E501
                .format(evaluation, allowed_values)
            )

        self._evaluation = evaluation

    @property
    def state(self):
        """Gets the state of this Test.  # noqa: E501


        :return: The state of this Test.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this Test.


        :param state: The state of this Test.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                state is not None and len(state) > 25):
            raise ValueError("Invalid value for `state`, length must be less than or equal to `25`")  # noqa: E501

        self._state = state

    @property
    def execution_time(self):
        """Gets the execution_time of this Test.  # noqa: E501


        :return: The execution_time of this Test.  # noqa: E501
        :rtype: str
        """
        return self._execution_time

    @execution_time.setter
    def execution_time(self, execution_time):
        """Sets the execution_time of this Test.


        :param execution_time: The execution_time of this Test.  # noqa: E501
        :type: str
        """

        self._execution_time = execution_time

    @property
    def created_date(self):
        """Gets the created_date of this Test.  # noqa: E501


        :return: The created_date of this Test.  # noqa: E501
        :rtype: datetime
        """
        return self._created_date

    @created_date.setter
    def created_date(self, created_date):
        """Sets the created_date of this Test.


        :param created_date: The created_date of this Test.  # noqa: E501
        :type: datetime
        """

        self._created_date = created_date

    @property
    def updated_date(self):
        """Gets the updated_date of this Test.  # noqa: E501


        :return: The updated_date of this Test.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_date

    @updated_date.setter
    def updated_date(self, updated_date):
        """Sets the updated_date of this Test.


        :param updated_date: The updated_date of this Test.  # noqa: E501
        :type: datetime
        """

        self._updated_date = updated_date

    @property
    def user(self):
        """Gets the user of this Test.  # noqa: E501


        :return: The user of this Test.  # noqa: E501
        :rtype: int
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this Test.


        :param user: The user of this Test.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and user is None:  # noqa: E501
            raise ValueError("Invalid value for `user`, must not be `None`")  # noqa: E501

        self._user = user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Test):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Test):
            return True

        return self.to_dict() != other.to_dict()
