# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from autoppia_backend_client.configuration import Configuration


class TrackingVS(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'document': 'Document',
        'action': 'str',
        'created_at': 'datetime',
        'embedding_database': 'int'
    }

    attribute_map = {
        'id': 'id',
        'document': 'document',
        'action': 'action',
        'created_at': 'created_at',
        'embedding_database': 'embedding_database'
    }

    def __init__(self, id=None, document=None, action=None, created_at=None, embedding_database=None, local_vars_configuration=None):  # noqa: E501
        """TrackingVS - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._document = None
        self._action = None
        self._created_at = None
        self._embedding_database = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if document is not None:
            self.document = document
        if action is not None:
            self.action = action
        if created_at is not None:
            self.created_at = created_at
        self.embedding_database = embedding_database

    @property
    def id(self):
        """Gets the id of this TrackingVS.  # noqa: E501


        :return: The id of this TrackingVS.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TrackingVS.


        :param id: The id of this TrackingVS.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def document(self):
        """Gets the document of this TrackingVS.  # noqa: E501


        :return: The document of this TrackingVS.  # noqa: E501
        :rtype: Document
        """
        return self._document

    @document.setter
    def document(self, document):
        """Sets the document of this TrackingVS.


        :param document: The document of this TrackingVS.  # noqa: E501
        :type: Document
        """

        self._document = document

    @property
    def action(self):
        """Gets the action of this TrackingVS.  # noqa: E501


        :return: The action of this TrackingVS.  # noqa: E501
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this TrackingVS.


        :param action: The action of this TrackingVS.  # noqa: E501
        :type: str
        """
        allowed_values = ["created", "deleted"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and action not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `action` ({0}), must be one of {1}"  # noqa: E501
                .format(action, allowed_values)
            )

        self._action = action

    @property
    def created_at(self):
        """Gets the created_at of this TrackingVS.  # noqa: E501


        :return: The created_at of this TrackingVS.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this TrackingVS.


        :param created_at: The created_at of this TrackingVS.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def embedding_database(self):
        """Gets the embedding_database of this TrackingVS.  # noqa: E501


        :return: The embedding_database of this TrackingVS.  # noqa: E501
        :rtype: int
        """
        return self._embedding_database

    @embedding_database.setter
    def embedding_database(self, embedding_database):
        """Sets the embedding_database of this TrackingVS.


        :param embedding_database: The embedding_database of this TrackingVS.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and embedding_database is None:  # noqa: E501
            raise ValueError("Invalid value for `embedding_database`, must not be `None`")  # noqa: E501

        self._embedding_database = embedding_database

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TrackingVS):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TrackingVS):
            return True

        return self.to_dict() != other.to_dict()
