# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from autoppia_backend_client.configuration import Configuration


class UpdateUser(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'first_name': 'str',
        'last_name': 'str',
        'email': 'str',
        'username': 'str',
        'title': 'str',
        'company': 'str',
        'about': 'str',
        'phone_num': 'str',
        'country': 'str',
        'language': 'str'
    }

    attribute_map = {
        'first_name': 'first_name',
        'last_name': 'last_name',
        'email': 'email',
        'username': 'username',
        'title': 'title',
        'company': 'company',
        'about': 'about',
        'phone_num': 'phone_num',
        'country': 'country',
        'language': 'language'
    }

    def __init__(self, first_name=None, last_name=None, email=None, username=None, title=None, company=None, about=None, phone_num=None, country=None, language=None, local_vars_configuration=None):  # noqa: E501
        """UpdateUser - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._first_name = None
        self._last_name = None
        self._email = None
        self._username = None
        self._title = None
        self._company = None
        self._about = None
        self._phone_num = None
        self._country = None
        self._language = None
        self.discriminator = None

        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        self.email = email
        if username is not None:
            self.username = username
        self.title = title
        self.company = company
        self.about = about
        self.phone_num = phone_num
        if country is not None:
            self.country = country
        if language is not None:
            self.language = language

    @property
    def first_name(self):
        """Gets the first_name of this UpdateUser.  # noqa: E501


        :return: The first_name of this UpdateUser.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this UpdateUser.


        :param first_name: The first_name of this UpdateUser.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                first_name is not None and len(first_name) > 30):
            raise ValueError("Invalid value for `first_name`, length must be less than or equal to `30`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                first_name is not None and not re.search(r'^[a-zA-Z]*$', first_name)):  # noqa: E501
            raise ValueError(r"Invalid value for `first_name`, must be a follow pattern or equal to `/^[a-zA-Z]*$/`")  # noqa: E501

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this UpdateUser.  # noqa: E501


        :return: The last_name of this UpdateUser.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this UpdateUser.


        :param last_name: The last_name of this UpdateUser.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                last_name is not None and len(last_name) > 30):
            raise ValueError("Invalid value for `last_name`, length must be less than or equal to `30`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                last_name is not None and not re.search(r'^[a-zA-Z\s]+$', last_name)):  # noqa: E501
            raise ValueError(r"Invalid value for `last_name`, must be a follow pattern or equal to `/^[a-zA-Z\s]+$/`")  # noqa: E501

        self._last_name = last_name

    @property
    def email(self):
        """Gets the email of this UpdateUser.  # noqa: E501


        :return: The email of this UpdateUser.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UpdateUser.


        :param email: The email of this UpdateUser.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                email is not None and len(email) < 1):
            raise ValueError("Invalid value for `email`, length must be greater than or equal to `1`")  # noqa: E501

        self._email = email

    @property
    def username(self):
        """Gets the username of this UpdateUser.  # noqa: E501

        Automatically set to email or wallet_address.  # noqa: E501

        :return: The username of this UpdateUser.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this UpdateUser.

        Automatically set to email or wallet_address.  # noqa: E501

        :param username: The username of this UpdateUser.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                username is not None and len(username) > 255):
            raise ValueError("Invalid value for `username`, length must be less than or equal to `255`")  # noqa: E501

        self._username = username

    @property
    def title(self):
        """Gets the title of this UpdateUser.  # noqa: E501


        :return: The title of this UpdateUser.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this UpdateUser.


        :param title: The title of this UpdateUser.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                title is not None and len(title) > 255):
            raise ValueError("Invalid value for `title`, length must be less than or equal to `255`")  # noqa: E501

        self._title = title

    @property
    def company(self):
        """Gets the company of this UpdateUser.  # noqa: E501


        :return: The company of this UpdateUser.  # noqa: E501
        :rtype: str
        """
        return self._company

    @company.setter
    def company(self, company):
        """Sets the company of this UpdateUser.


        :param company: The company of this UpdateUser.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                company is not None and len(company) > 255):
            raise ValueError("Invalid value for `company`, length must be less than or equal to `255`")  # noqa: E501

        self._company = company

    @property
    def about(self):
        """Gets the about of this UpdateUser.  # noqa: E501


        :return: The about of this UpdateUser.  # noqa: E501
        :rtype: str
        """
        return self._about

    @about.setter
    def about(self, about):
        """Sets the about of this UpdateUser.


        :param about: The about of this UpdateUser.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                about is not None and len(about) > 255):
            raise ValueError("Invalid value for `about`, length must be less than or equal to `255`")  # noqa: E501

        self._about = about

    @property
    def phone_num(self):
        """Gets the phone_num of this UpdateUser.  # noqa: E501


        :return: The phone_num of this UpdateUser.  # noqa: E501
        :rtype: str
        """
        return self._phone_num

    @phone_num.setter
    def phone_num(self, phone_num):
        """Sets the phone_num of this UpdateUser.


        :param phone_num: The phone_num of this UpdateUser.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                phone_num is not None and len(phone_num) > 255):
            raise ValueError("Invalid value for `phone_num`, length must be less than or equal to `255`")  # noqa: E501

        self._phone_num = phone_num

    @property
    def country(self):
        """Gets the country of this UpdateUser.  # noqa: E501


        :return: The country of this UpdateUser.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this UpdateUser.


        :param country: The country of this UpdateUser.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                country is not None and len(country) > 255):
            raise ValueError("Invalid value for `country`, length must be less than or equal to `255`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                country is not None and len(country) < 1):
            raise ValueError("Invalid value for `country`, length must be greater than or equal to `1`")  # noqa: E501

        self._country = country

    @property
    def language(self):
        """Gets the language of this UpdateUser.  # noqa: E501


        :return: The language of this UpdateUser.  # noqa: E501
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this UpdateUser.


        :param language: The language of this UpdateUser.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                language is not None and len(language) > 255):
            raise ValueError("Invalid value for `language`, length must be less than or equal to `255`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                language is not None and len(language) < 1):
            raise ValueError("Invalid value for `language`, length must be greater than or equal to `1`")  # noqa: E501

        self._language = language

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateUser):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UpdateUser):
            return True

        return self.to_dict() != other.to_dict()
