# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from autoppia_backend_client.configuration import Configuration


class UserLLMModel(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'llm_model': 'LLMModel',
        'llm_model_id': 'int',
        'api_key': 'Credential',
        'api_key_id': 'int',
        'created_at': 'datetime',
        'updated_at': 'datetime',
        'active': 'bool',
        'user': 'int'
    }

    attribute_map = {
        'id': 'id',
        'llm_model': 'llm_model',
        'llm_model_id': 'llm_model_id',
        'api_key': 'api_key',
        'api_key_id': 'api_key_id',
        'created_at': 'created_at',
        'updated_at': 'updated_at',
        'active': 'active',
        'user': 'user'
    }

    def __init__(self, id=None, llm_model=None, llm_model_id=None, api_key=None, api_key_id=None, created_at=None, updated_at=None, active=None, user=None, local_vars_configuration=None):  # noqa: E501
        """UserLLMModel - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._llm_model = None
        self._llm_model_id = None
        self._api_key = None
        self._api_key_id = None
        self._created_at = None
        self._updated_at = None
        self._active = None
        self._user = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if llm_model is not None:
            self.llm_model = llm_model
        if llm_model_id is not None:
            self.llm_model_id = llm_model_id
        if api_key is not None:
            self.api_key = api_key
        if api_key_id is not None:
            self.api_key_id = api_key_id
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at
        if active is not None:
            self.active = active
        if user is not None:
            self.user = user

    @property
    def id(self):
        """Gets the id of this UserLLMModel.  # noqa: E501


        :return: The id of this UserLLMModel.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UserLLMModel.


        :param id: The id of this UserLLMModel.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def llm_model(self):
        """Gets the llm_model of this UserLLMModel.  # noqa: E501


        :return: The llm_model of this UserLLMModel.  # noqa: E501
        :rtype: LLMModel
        """
        return self._llm_model

    @llm_model.setter
    def llm_model(self, llm_model):
        """Sets the llm_model of this UserLLMModel.


        :param llm_model: The llm_model of this UserLLMModel.  # noqa: E501
        :type: LLMModel
        """

        self._llm_model = llm_model

    @property
    def llm_model_id(self):
        """Gets the llm_model_id of this UserLLMModel.  # noqa: E501


        :return: The llm_model_id of this UserLLMModel.  # noqa: E501
        :rtype: int
        """
        return self._llm_model_id

    @llm_model_id.setter
    def llm_model_id(self, llm_model_id):
        """Sets the llm_model_id of this UserLLMModel.


        :param llm_model_id: The llm_model_id of this UserLLMModel.  # noqa: E501
        :type: int
        """

        self._llm_model_id = llm_model_id

    @property
    def api_key(self):
        """Gets the api_key of this UserLLMModel.  # noqa: E501


        :return: The api_key of this UserLLMModel.  # noqa: E501
        :rtype: Credential
        """
        return self._api_key

    @api_key.setter
    def api_key(self, api_key):
        """Sets the api_key of this UserLLMModel.


        :param api_key: The api_key of this UserLLMModel.  # noqa: E501
        :type: Credential
        """

        self._api_key = api_key

    @property
    def api_key_id(self):
        """Gets the api_key_id of this UserLLMModel.  # noqa: E501


        :return: The api_key_id of this UserLLMModel.  # noqa: E501
        :rtype: int
        """
        return self._api_key_id

    @api_key_id.setter
    def api_key_id(self, api_key_id):
        """Sets the api_key_id of this UserLLMModel.


        :param api_key_id: The api_key_id of this UserLLMModel.  # noqa: E501
        :type: int
        """

        self._api_key_id = api_key_id

    @property
    def created_at(self):
        """Gets the created_at of this UserLLMModel.  # noqa: E501


        :return: The created_at of this UserLLMModel.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this UserLLMModel.


        :param created_at: The created_at of this UserLLMModel.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this UserLLMModel.  # noqa: E501


        :return: The updated_at of this UserLLMModel.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this UserLLMModel.


        :param updated_at: The updated_at of this UserLLMModel.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def active(self):
        """Gets the active of this UserLLMModel.  # noqa: E501


        :return: The active of this UserLLMModel.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this UserLLMModel.


        :param active: The active of this UserLLMModel.  # noqa: E501
        :type: bool
        """

        self._active = active

    @property
    def user(self):
        """Gets the user of this UserLLMModel.  # noqa: E501


        :return: The user of this UserLLMModel.  # noqa: E501
        :rtype: int
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this UserLLMModel.


        :param user: The user of this UserLLMModel.  # noqa: E501
        :type: int
        """

        self._user = user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserLLMModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserLLMModel):
            return True

        return self.to_dict() != other.to_dict()
