# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from autoppia_backend_client.configuration import Configuration


class UserIntegration(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'user': 'int',
        'name': 'str',
        'integration': 'int',
        'active': 'bool',
        'user_integration_attributes': 'list[UserIntegrationAttribute]'
    }

    attribute_map = {
        'id': 'id',
        'user': 'user',
        'name': 'name',
        'integration': 'integration',
        'active': 'active',
        'user_integration_attributes': 'user_integration_attributes'
    }

    def __init__(self, id=None, user=None, name=None, integration=None, active=None, user_integration_attributes=None, local_vars_configuration=None):  # noqa: E501
        """UserIntegration - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._user = None
        self._name = None
        self._integration = None
        self._active = None
        self._user_integration_attributes = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if user is not None:
            self.user = user
        self.name = name
        self.integration = integration
        if active is not None:
            self.active = active
        self.user_integration_attributes = user_integration_attributes

    @property
    def id(self):
        """Gets the id of this UserIntegration.  # noqa: E501


        :return: The id of this UserIntegration.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UserIntegration.


        :param id: The id of this UserIntegration.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def user(self):
        """Gets the user of this UserIntegration.  # noqa: E501


        :return: The user of this UserIntegration.  # noqa: E501
        :rtype: int
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this UserIntegration.


        :param user: The user of this UserIntegration.  # noqa: E501
        :type: int
        """

        self._user = user

    @property
    def name(self):
        """Gets the name of this UserIntegration.  # noqa: E501


        :return: The name of this UserIntegration.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UserIntegration.


        :param name: The name of this UserIntegration.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) > 255):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `255`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def integration(self):
        """Gets the integration of this UserIntegration.  # noqa: E501


        :return: The integration of this UserIntegration.  # noqa: E501
        :rtype: int
        """
        return self._integration

    @integration.setter
    def integration(self, integration):
        """Sets the integration of this UserIntegration.


        :param integration: The integration of this UserIntegration.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and integration is None:  # noqa: E501
            raise ValueError("Invalid value for `integration`, must not be `None`")  # noqa: E501

        self._integration = integration

    @property
    def active(self):
        """Gets the active of this UserIntegration.  # noqa: E501


        :return: The active of this UserIntegration.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this UserIntegration.


        :param active: The active of this UserIntegration.  # noqa: E501
        :type: bool
        """

        self._active = active

    @property
    def user_integration_attributes(self):
        """Gets the user_integration_attributes of this UserIntegration.  # noqa: E501


        :return: The user_integration_attributes of this UserIntegration.  # noqa: E501
        :rtype: list[UserIntegrationAttribute]
        """
        return self._user_integration_attributes

    @user_integration_attributes.setter
    def user_integration_attributes(self, user_integration_attributes):
        """Sets the user_integration_attributes of this UserIntegration.


        :param user_integration_attributes: The user_integration_attributes of this UserIntegration.  # noqa: E501
        :type: list[UserIntegrationAttribute]
        """
        if self.local_vars_configuration.client_side_validation and user_integration_attributes is None:  # noqa: E501
            raise ValueError("Invalid value for `user_integration_attributes`, must not be `None`")  # noqa: E501

        self._user_integration_attributes = user_integration_attributes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserIntegration):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserIntegration):
            return True

        return self.to_dict() != other.to_dict()
