# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from autoppia_backend_client.configuration import Configuration


class WorkerLog(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'worker_config': 'int',
        'worker_name': 'str',
        'event_type': 'str',
        'level': 'str',
        'session_id': 'str',
        'task_id': 'str',
        'message': 'str',
        'input_content': 'str',
        'output_content': 'str',
        'tool_name': 'str',
        'tool_arguments': 'object',
        'tool_result': 'str',
        'llm_provider': 'str',
        'llm_model': 'str',
        'input_tokens': 'int',
        'output_tokens': 'int',
        'llm_latency_ms': 'int',
        'duration_ms': 'int',
        'metadata': 'object',
        'error_message': 'str',
        'created_at': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'worker_config': 'worker_config',
        'worker_name': 'worker_name',
        'event_type': 'event_type',
        'level': 'level',
        'session_id': 'session_id',
        'task_id': 'task_id',
        'message': 'message',
        'input_content': 'input_content',
        'output_content': 'output_content',
        'tool_name': 'tool_name',
        'tool_arguments': 'tool_arguments',
        'tool_result': 'tool_result',
        'llm_provider': 'llm_provider',
        'llm_model': 'llm_model',
        'input_tokens': 'input_tokens',
        'output_tokens': 'output_tokens',
        'llm_latency_ms': 'llm_latency_ms',
        'duration_ms': 'duration_ms',
        'metadata': 'metadata',
        'error_message': 'error_message',
        'created_at': 'created_at'
    }

    def __init__(self, id=None, worker_config=None, worker_name=None, event_type=None, level=None, session_id=None, task_id=None, message=None, input_content=None, output_content=None, tool_name=None, tool_arguments=None, tool_result=None, llm_provider=None, llm_model=None, input_tokens=None, output_tokens=None, llm_latency_ms=None, duration_ms=None, metadata=None, error_message=None, created_at=None, local_vars_configuration=None):  # noqa: E501
        """WorkerLog - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._worker_config = None
        self._worker_name = None
        self._event_type = None
        self._level = None
        self._session_id = None
        self._task_id = None
        self._message = None
        self._input_content = None
        self._output_content = None
        self._tool_name = None
        self._tool_arguments = None
        self._tool_result = None
        self._llm_provider = None
        self._llm_model = None
        self._input_tokens = None
        self._output_tokens = None
        self._llm_latency_ms = None
        self._duration_ms = None
        self._metadata = None
        self._error_message = None
        self._created_at = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if worker_config is not None:
            self.worker_config = worker_config
        if worker_name is not None:
            self.worker_name = worker_name
        if event_type is not None:
            self.event_type = event_type
        if level is not None:
            self.level = level
        self.session_id = session_id
        self.task_id = task_id
        self.message = message
        self.input_content = input_content
        self.output_content = output_content
        self.tool_name = tool_name
        self.tool_arguments = tool_arguments
        self.tool_result = tool_result
        self.llm_provider = llm_provider
        self.llm_model = llm_model
        if input_tokens is not None:
            self.input_tokens = input_tokens
        if output_tokens is not None:
            self.output_tokens = output_tokens
        if llm_latency_ms is not None:
            self.llm_latency_ms = llm_latency_ms
        if duration_ms is not None:
            self.duration_ms = duration_ms
        self.metadata = metadata
        self.error_message = error_message
        if created_at is not None:
            self.created_at = created_at

    @property
    def id(self):
        """Gets the id of this WorkerLog.  # noqa: E501


        :return: The id of this WorkerLog.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this WorkerLog.


        :param id: The id of this WorkerLog.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def worker_config(self):
        """Gets the worker_config of this WorkerLog.  # noqa: E501


        :return: The worker_config of this WorkerLog.  # noqa: E501
        :rtype: int
        """
        return self._worker_config

    @worker_config.setter
    def worker_config(self, worker_config):
        """Sets the worker_config of this WorkerLog.


        :param worker_config: The worker_config of this WorkerLog.  # noqa: E501
        :type: int
        """

        self._worker_config = worker_config

    @property
    def worker_name(self):
        """Gets the worker_name of this WorkerLog.  # noqa: E501


        :return: The worker_name of this WorkerLog.  # noqa: E501
        :rtype: str
        """
        return self._worker_name

    @worker_name.setter
    def worker_name(self, worker_name):
        """Sets the worker_name of this WorkerLog.


        :param worker_name: The worker_name of this WorkerLog.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                worker_name is not None and len(worker_name) < 1):
            raise ValueError("Invalid value for `worker_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._worker_name = worker_name

    @property
    def event_type(self):
        """Gets the event_type of this WorkerLog.  # noqa: E501


        :return: The event_type of this WorkerLog.  # noqa: E501
        :rtype: str
        """
        return self._event_type

    @event_type.setter
    def event_type(self, event_type):
        """Sets the event_type of this WorkerLog.


        :param event_type: The event_type of this WorkerLog.  # noqa: E501
        :type: str
        """
        allowed_values = ["connect", "disconnect", "task_start", "task_complete", "task_error", "tool_call", "tool_result", "tool_error", "llm_request", "llm_response", "health_check", "error"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and event_type not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `event_type` ({0}), must be one of {1}"  # noqa: E501
                .format(event_type, allowed_values)
            )

        self._event_type = event_type

    @property
    def level(self):
        """Gets the level of this WorkerLog.  # noqa: E501


        :return: The level of this WorkerLog.  # noqa: E501
        :rtype: str
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this WorkerLog.


        :param level: The level of this WorkerLog.  # noqa: E501
        :type: str
        """
        allowed_values = ["debug", "info", "warning", "error"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and level not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `level` ({0}), must be one of {1}"  # noqa: E501
                .format(level, allowed_values)
            )

        self._level = level

    @property
    def session_id(self):
        """Gets the session_id of this WorkerLog.  # noqa: E501


        :return: The session_id of this WorkerLog.  # noqa: E501
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id):
        """Sets the session_id of this WorkerLog.


        :param session_id: The session_id of this WorkerLog.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                session_id is not None and len(session_id) < 1):
            raise ValueError("Invalid value for `session_id`, length must be greater than or equal to `1`")  # noqa: E501

        self._session_id = session_id

    @property
    def task_id(self):
        """Gets the task_id of this WorkerLog.  # noqa: E501


        :return: The task_id of this WorkerLog.  # noqa: E501
        :rtype: str
        """
        return self._task_id

    @task_id.setter
    def task_id(self, task_id):
        """Sets the task_id of this WorkerLog.


        :param task_id: The task_id of this WorkerLog.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                task_id is not None and len(task_id) < 1):
            raise ValueError("Invalid value for `task_id`, length must be greater than or equal to `1`")  # noqa: E501

        self._task_id = task_id

    @property
    def message(self):
        """Gets the message of this WorkerLog.  # noqa: E501


        :return: The message of this WorkerLog.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this WorkerLog.


        :param message: The message of this WorkerLog.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                message is not None and len(message) < 1):
            raise ValueError("Invalid value for `message`, length must be greater than or equal to `1`")  # noqa: E501

        self._message = message

    @property
    def input_content(self):
        """Gets the input_content of this WorkerLog.  # noqa: E501


        :return: The input_content of this WorkerLog.  # noqa: E501
        :rtype: str
        """
        return self._input_content

    @input_content.setter
    def input_content(self, input_content):
        """Sets the input_content of this WorkerLog.


        :param input_content: The input_content of this WorkerLog.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                input_content is not None and len(input_content) < 1):
            raise ValueError("Invalid value for `input_content`, length must be greater than or equal to `1`")  # noqa: E501

        self._input_content = input_content

    @property
    def output_content(self):
        """Gets the output_content of this WorkerLog.  # noqa: E501


        :return: The output_content of this WorkerLog.  # noqa: E501
        :rtype: str
        """
        return self._output_content

    @output_content.setter
    def output_content(self, output_content):
        """Sets the output_content of this WorkerLog.


        :param output_content: The output_content of this WorkerLog.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                output_content is not None and len(output_content) < 1):
            raise ValueError("Invalid value for `output_content`, length must be greater than or equal to `1`")  # noqa: E501

        self._output_content = output_content

    @property
    def tool_name(self):
        """Gets the tool_name of this WorkerLog.  # noqa: E501


        :return: The tool_name of this WorkerLog.  # noqa: E501
        :rtype: str
        """
        return self._tool_name

    @tool_name.setter
    def tool_name(self, tool_name):
        """Sets the tool_name of this WorkerLog.


        :param tool_name: The tool_name of this WorkerLog.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                tool_name is not None and len(tool_name) < 1):
            raise ValueError("Invalid value for `tool_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._tool_name = tool_name

    @property
    def tool_arguments(self):
        """Gets the tool_arguments of this WorkerLog.  # noqa: E501


        :return: The tool_arguments of this WorkerLog.  # noqa: E501
        :rtype: object
        """
        return self._tool_arguments

    @tool_arguments.setter
    def tool_arguments(self, tool_arguments):
        """Sets the tool_arguments of this WorkerLog.


        :param tool_arguments: The tool_arguments of this WorkerLog.  # noqa: E501
        :type: object
        """

        self._tool_arguments = tool_arguments

    @property
    def tool_result(self):
        """Gets the tool_result of this WorkerLog.  # noqa: E501


        :return: The tool_result of this WorkerLog.  # noqa: E501
        :rtype: str
        """
        return self._tool_result

    @tool_result.setter
    def tool_result(self, tool_result):
        """Sets the tool_result of this WorkerLog.


        :param tool_result: The tool_result of this WorkerLog.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                tool_result is not None and len(tool_result) < 1):
            raise ValueError("Invalid value for `tool_result`, length must be greater than or equal to `1`")  # noqa: E501

        self._tool_result = tool_result

    @property
    def llm_provider(self):
        """Gets the llm_provider of this WorkerLog.  # noqa: E501


        :return: The llm_provider of this WorkerLog.  # noqa: E501
        :rtype: str
        """
        return self._llm_provider

    @llm_provider.setter
    def llm_provider(self, llm_provider):
        """Sets the llm_provider of this WorkerLog.


        :param llm_provider: The llm_provider of this WorkerLog.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                llm_provider is not None and len(llm_provider) < 1):
            raise ValueError("Invalid value for `llm_provider`, length must be greater than or equal to `1`")  # noqa: E501

        self._llm_provider = llm_provider

    @property
    def llm_model(self):
        """Gets the llm_model of this WorkerLog.  # noqa: E501


        :return: The llm_model of this WorkerLog.  # noqa: E501
        :rtype: str
        """
        return self._llm_model

    @llm_model.setter
    def llm_model(self, llm_model):
        """Sets the llm_model of this WorkerLog.


        :param llm_model: The llm_model of this WorkerLog.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                llm_model is not None and len(llm_model) < 1):
            raise ValueError("Invalid value for `llm_model`, length must be greater than or equal to `1`")  # noqa: E501

        self._llm_model = llm_model

    @property
    def input_tokens(self):
        """Gets the input_tokens of this WorkerLog.  # noqa: E501


        :return: The input_tokens of this WorkerLog.  # noqa: E501
        :rtype: int
        """
        return self._input_tokens

    @input_tokens.setter
    def input_tokens(self, input_tokens):
        """Sets the input_tokens of this WorkerLog.


        :param input_tokens: The input_tokens of this WorkerLog.  # noqa: E501
        :type: int
        """

        self._input_tokens = input_tokens

    @property
    def output_tokens(self):
        """Gets the output_tokens of this WorkerLog.  # noqa: E501


        :return: The output_tokens of this WorkerLog.  # noqa: E501
        :rtype: int
        """
        return self._output_tokens

    @output_tokens.setter
    def output_tokens(self, output_tokens):
        """Sets the output_tokens of this WorkerLog.


        :param output_tokens: The output_tokens of this WorkerLog.  # noqa: E501
        :type: int
        """

        self._output_tokens = output_tokens

    @property
    def llm_latency_ms(self):
        """Gets the llm_latency_ms of this WorkerLog.  # noqa: E501


        :return: The llm_latency_ms of this WorkerLog.  # noqa: E501
        :rtype: int
        """
        return self._llm_latency_ms

    @llm_latency_ms.setter
    def llm_latency_ms(self, llm_latency_ms):
        """Sets the llm_latency_ms of this WorkerLog.


        :param llm_latency_ms: The llm_latency_ms of this WorkerLog.  # noqa: E501
        :type: int
        """

        self._llm_latency_ms = llm_latency_ms

    @property
    def duration_ms(self):
        """Gets the duration_ms of this WorkerLog.  # noqa: E501


        :return: The duration_ms of this WorkerLog.  # noqa: E501
        :rtype: int
        """
        return self._duration_ms

    @duration_ms.setter
    def duration_ms(self, duration_ms):
        """Sets the duration_ms of this WorkerLog.


        :param duration_ms: The duration_ms of this WorkerLog.  # noqa: E501
        :type: int
        """

        self._duration_ms = duration_ms

    @property
    def metadata(self):
        """Gets the metadata of this WorkerLog.  # noqa: E501


        :return: The metadata of this WorkerLog.  # noqa: E501
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this WorkerLog.


        :param metadata: The metadata of this WorkerLog.  # noqa: E501
        :type: object
        """

        self._metadata = metadata

    @property
    def error_message(self):
        """Gets the error_message of this WorkerLog.  # noqa: E501


        :return: The error_message of this WorkerLog.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this WorkerLog.


        :param error_message: The error_message of this WorkerLog.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                error_message is not None and len(error_message) < 1):
            raise ValueError("Invalid value for `error_message`, length must be greater than or equal to `1`")  # noqa: E501

        self._error_message = error_message

    @property
    def created_at(self):
        """Gets the created_at of this WorkerLog.  # noqa: E501


        :return: The created_at of this WorkerLog.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this WorkerLog.


        :param created_at: The created_at of this WorkerLog.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkerLog):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, WorkerLog):
            return True

        return self.to_dict() != other.to_dict()
