# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from autoppia_backend_client.configuration import Configuration


class Worker(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'user_llm_model': 'UserLLMModel',
        'user_llm_model_id': 'int',
        'embedding_database': 'EmbeddingDatabase',
        'embedding_database_id': 'int',
        'user_configuration': 'list[ListUserConfiguration]',
        'user_configuration_ids': 'list[int]',
        'system_prompt': 'Prompt',
        'system_prompt_id': 'int',
        'name': 'str',
        'mode': 'str',
        'created_date': 'datetime',
        'updated_date': 'datetime',
        'state': 'bool',
        'avatar': 'str',
        'agent': 'str',
        'user': 'int',
        'user_toolkit': 'list[int]'
    }

    attribute_map = {
        'id': 'id',
        'user_llm_model': 'user_llm_model',
        'user_llm_model_id': 'user_llm_model_id',
        'embedding_database': 'embedding_database',
        'embedding_database_id': 'embedding_database_id',
        'user_configuration': 'user_configuration',
        'user_configuration_ids': 'user_configuration_ids',
        'system_prompt': 'system_prompt',
        'system_prompt_id': 'system_prompt_id',
        'name': 'name',
        'mode': 'mode',
        'created_date': 'created_date',
        'updated_date': 'updated_date',
        'state': 'state',
        'avatar': 'avatar',
        'agent': 'agent',
        'user': 'user',
        'user_toolkit': 'user_toolkit'
    }

    def __init__(self, id=None, user_llm_model=None, user_llm_model_id=None, embedding_database=None, embedding_database_id=None, user_configuration=None, user_configuration_ids=None, system_prompt=None, system_prompt_id=None, name=None, mode=None, created_date=None, updated_date=None, state=None, avatar=None, agent=None, user=None, user_toolkit=None, local_vars_configuration=None):  # noqa: E501
        """Worker - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._user_llm_model = None
        self._user_llm_model_id = None
        self._embedding_database = None
        self._embedding_database_id = None
        self._user_configuration = None
        self._user_configuration_ids = None
        self._system_prompt = None
        self._system_prompt_id = None
        self._name = None
        self._mode = None
        self._created_date = None
        self._updated_date = None
        self._state = None
        self._avatar = None
        self._agent = None
        self._user = None
        self._user_toolkit = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if user_llm_model is not None:
            self.user_llm_model = user_llm_model
        if user_llm_model_id is not None:
            self.user_llm_model_id = user_llm_model_id
        if embedding_database is not None:
            self.embedding_database = embedding_database
        if embedding_database_id is not None:
            self.embedding_database_id = embedding_database_id
        if user_configuration is not None:
            self.user_configuration = user_configuration
        if user_configuration_ids is not None:
            self.user_configuration_ids = user_configuration_ids
        if system_prompt is not None:
            self.system_prompt = system_prompt
        if system_prompt_id is not None:
            self.system_prompt_id = system_prompt_id
        self.name = name
        self.mode = mode
        if created_date is not None:
            self.created_date = created_date
        if updated_date is not None:
            self.updated_date = updated_date
        if state is not None:
            self.state = state
        self.avatar = avatar
        self.agent = agent
        self.user = user
        if user_toolkit is not None:
            self.user_toolkit = user_toolkit

    @property
    def id(self):
        """Gets the id of this Worker.  # noqa: E501


        :return: The id of this Worker.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Worker.


        :param id: The id of this Worker.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def user_llm_model(self):
        """Gets the user_llm_model of this Worker.  # noqa: E501


        :return: The user_llm_model of this Worker.  # noqa: E501
        :rtype: UserLLMModel
        """
        return self._user_llm_model

    @user_llm_model.setter
    def user_llm_model(self, user_llm_model):
        """Sets the user_llm_model of this Worker.


        :param user_llm_model: The user_llm_model of this Worker.  # noqa: E501
        :type: UserLLMModel
        """

        self._user_llm_model = user_llm_model

    @property
    def user_llm_model_id(self):
        """Gets the user_llm_model_id of this Worker.  # noqa: E501


        :return: The user_llm_model_id of this Worker.  # noqa: E501
        :rtype: int
        """
        return self._user_llm_model_id

    @user_llm_model_id.setter
    def user_llm_model_id(self, user_llm_model_id):
        """Sets the user_llm_model_id of this Worker.


        :param user_llm_model_id: The user_llm_model_id of this Worker.  # noqa: E501
        :type: int
        """

        self._user_llm_model_id = user_llm_model_id

    @property
    def embedding_database(self):
        """Gets the embedding_database of this Worker.  # noqa: E501


        :return: The embedding_database of this Worker.  # noqa: E501
        :rtype: EmbeddingDatabase
        """
        return self._embedding_database

    @embedding_database.setter
    def embedding_database(self, embedding_database):
        """Sets the embedding_database of this Worker.


        :param embedding_database: The embedding_database of this Worker.  # noqa: E501
        :type: EmbeddingDatabase
        """

        self._embedding_database = embedding_database

    @property
    def embedding_database_id(self):
        """Gets the embedding_database_id of this Worker.  # noqa: E501


        :return: The embedding_database_id of this Worker.  # noqa: E501
        :rtype: int
        """
        return self._embedding_database_id

    @embedding_database_id.setter
    def embedding_database_id(self, embedding_database_id):
        """Sets the embedding_database_id of this Worker.


        :param embedding_database_id: The embedding_database_id of this Worker.  # noqa: E501
        :type: int
        """

        self._embedding_database_id = embedding_database_id

    @property
    def user_configuration(self):
        """Gets the user_configuration of this Worker.  # noqa: E501


        :return: The user_configuration of this Worker.  # noqa: E501
        :rtype: list[ListUserConfiguration]
        """
        return self._user_configuration

    @user_configuration.setter
    def user_configuration(self, user_configuration):
        """Sets the user_configuration of this Worker.


        :param user_configuration: The user_configuration of this Worker.  # noqa: E501
        :type: list[ListUserConfiguration]
        """

        self._user_configuration = user_configuration

    @property
    def user_configuration_ids(self):
        """Gets the user_configuration_ids of this Worker.  # noqa: E501


        :return: The user_configuration_ids of this Worker.  # noqa: E501
        :rtype: list[int]
        """
        return self._user_configuration_ids

    @user_configuration_ids.setter
    def user_configuration_ids(self, user_configuration_ids):
        """Sets the user_configuration_ids of this Worker.


        :param user_configuration_ids: The user_configuration_ids of this Worker.  # noqa: E501
        :type: list[int]
        """

        self._user_configuration_ids = user_configuration_ids

    @property
    def system_prompt(self):
        """Gets the system_prompt of this Worker.  # noqa: E501


        :return: The system_prompt of this Worker.  # noqa: E501
        :rtype: Prompt
        """
        return self._system_prompt

    @system_prompt.setter
    def system_prompt(self, system_prompt):
        """Sets the system_prompt of this Worker.


        :param system_prompt: The system_prompt of this Worker.  # noqa: E501
        :type: Prompt
        """

        self._system_prompt = system_prompt

    @property
    def system_prompt_id(self):
        """Gets the system_prompt_id of this Worker.  # noqa: E501


        :return: The system_prompt_id of this Worker.  # noqa: E501
        :rtype: int
        """
        return self._system_prompt_id

    @system_prompt_id.setter
    def system_prompt_id(self, system_prompt_id):
        """Sets the system_prompt_id of this Worker.


        :param system_prompt_id: The system_prompt_id of this Worker.  # noqa: E501
        :type: int
        """

        self._system_prompt_id = system_prompt_id

    @property
    def name(self):
        """Gets the name of this Worker.  # noqa: E501


        :return: The name of this Worker.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Worker.


        :param name: The name of this Worker.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) > 255):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `255`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def mode(self):
        """Gets the mode of this Worker.  # noqa: E501


        :return: The mode of this Worker.  # noqa: E501
        :rtype: str
        """
        return self._mode

    @mode.setter
    def mode(self, mode):
        """Sets the mode of this Worker.


        :param mode: The mode of this Worker.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and mode is None:  # noqa: E501
            raise ValueError("Invalid value for `mode`, must not be `None`")  # noqa: E501
        allowed_values = ["assistant", "autonomous"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and mode not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `mode` ({0}), must be one of {1}"  # noqa: E501
                .format(mode, allowed_values)
            )

        self._mode = mode

    @property
    def created_date(self):
        """Gets the created_date of this Worker.  # noqa: E501


        :return: The created_date of this Worker.  # noqa: E501
        :rtype: datetime
        """
        return self._created_date

    @created_date.setter
    def created_date(self, created_date):
        """Sets the created_date of this Worker.


        :param created_date: The created_date of this Worker.  # noqa: E501
        :type: datetime
        """

        self._created_date = created_date

    @property
    def updated_date(self):
        """Gets the updated_date of this Worker.  # noqa: E501


        :return: The updated_date of this Worker.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_date

    @updated_date.setter
    def updated_date(self, updated_date):
        """Sets the updated_date of this Worker.


        :param updated_date: The updated_date of this Worker.  # noqa: E501
        :type: datetime
        """

        self._updated_date = updated_date

    @property
    def state(self):
        """Gets the state of this Worker.  # noqa: E501


        :return: The state of this Worker.  # noqa: E501
        :rtype: bool
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this Worker.


        :param state: The state of this Worker.  # noqa: E501
        :type: bool
        """

        self._state = state

    @property
    def avatar(self):
        """Gets the avatar of this Worker.  # noqa: E501


        :return: The avatar of this Worker.  # noqa: E501
        :rtype: str
        """
        return self._avatar

    @avatar.setter
    def avatar(self, avatar):
        """Sets the avatar of this Worker.


        :param avatar: The avatar of this Worker.  # noqa: E501
        :type: str
        """

        self._avatar = avatar

    @property
    def agent(self):
        """Gets the agent of this Worker.  # noqa: E501


        :return: The agent of this Worker.  # noqa: E501
        :rtype: str
        """
        return self._agent

    @agent.setter
    def agent(self, agent):
        """Sets the agent of this Worker.


        :param agent: The agent of this Worker.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                agent is not None and len(agent) > 255):
            raise ValueError("Invalid value for `agent`, length must be less than or equal to `255`")  # noqa: E501

        self._agent = agent

    @property
    def user(self):
        """Gets the user of this Worker.  # noqa: E501


        :return: The user of this Worker.  # noqa: E501
        :rtype: int
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this Worker.


        :param user: The user of this Worker.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and user is None:  # noqa: E501
            raise ValueError("Invalid value for `user`, must not be `None`")  # noqa: E501

        self._user = user

    @property
    def user_toolkit(self):
        """Gets the user_toolkit of this Worker.  # noqa: E501


        :return: The user_toolkit of this Worker.  # noqa: E501
        :rtype: list[int]
        """
        return self._user_toolkit

    @user_toolkit.setter
    def user_toolkit(self, user_toolkit):
        """Sets the user_toolkit of this Worker.


        :param user_toolkit: The user_toolkit of this Worker.  # noqa: E501
        :type: list[int]
        """

        self._user_toolkit = user_toolkit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Worker):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Worker):
            return True

        return self.to_dict() != other.to_dict()
