# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from autoppia_backend_client.configuration import Configuration


class Workspace(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'name': 'str',
        'description': 'str',
        'mission': 'str',
        'status': 'str',
        'graph': 'object',
        'execution_graph': 'object',
        'created_date': 'datetime',
        'updated_date': 'datetime',
        'user': 'int',
        'core_worker': 'int'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'description': 'description',
        'mission': 'mission',
        'status': 'status',
        'graph': 'graph',
        'execution_graph': 'execution_graph',
        'created_date': 'created_date',
        'updated_date': 'updated_date',
        'user': 'user',
        'core_worker': 'core_worker'
    }

    def __init__(self, id=None, name=None, description=None, mission=None, status=None, graph=None, execution_graph=None, created_date=None, updated_date=None, user=None, core_worker=None, local_vars_configuration=None):  # noqa: E501
        """Workspace - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._description = None
        self._mission = None
        self._status = None
        self._graph = None
        self._execution_graph = None
        self._created_date = None
        self._updated_date = None
        self._user = None
        self._core_worker = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.name = name
        self.description = description
        self.mission = mission
        if status is not None:
            self.status = status
        if graph is not None:
            self.graph = graph
        if execution_graph is not None:
            self.execution_graph = execution_graph
        if created_date is not None:
            self.created_date = created_date
        if updated_date is not None:
            self.updated_date = updated_date
        if user is not None:
            self.user = user
        self.core_worker = core_worker

    @property
    def id(self):
        """Gets the id of this Workspace.  # noqa: E501


        :return: The id of this Workspace.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Workspace.


        :param id: The id of this Workspace.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Workspace.  # noqa: E501


        :return: The name of this Workspace.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Workspace.


        :param name: The name of this Workspace.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) > 255):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `255`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this Workspace.  # noqa: E501


        :return: The description of this Workspace.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Workspace.


        :param description: The description of this Workspace.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def mission(self):
        """Gets the mission of this Workspace.  # noqa: E501


        :return: The mission of this Workspace.  # noqa: E501
        :rtype: str
        """
        return self._mission

    @mission.setter
    def mission(self, mission):
        """Sets the mission of this Workspace.


        :param mission: The mission of this Workspace.  # noqa: E501
        :type: str
        """

        self._mission = mission

    @property
    def status(self):
        """Gets the status of this Workspace.  # noqa: E501


        :return: The status of this Workspace.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Workspace.


        :param status: The status of this Workspace.  # noqa: E501
        :type: str
        """
        allowed_values = ["draft", "deployed", "paused"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and status not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def graph(self):
        """Gets the graph of this Workspace.  # noqa: E501


        :return: The graph of this Workspace.  # noqa: E501
        :rtype: object
        """
        return self._graph

    @graph.setter
    def graph(self, graph):
        """Sets the graph of this Workspace.


        :param graph: The graph of this Workspace.  # noqa: E501
        :type: object
        """

        self._graph = graph

    @property
    def execution_graph(self):
        """Gets the execution_graph of this Workspace.  # noqa: E501


        :return: The execution_graph of this Workspace.  # noqa: E501
        :rtype: object
        """
        return self._execution_graph

    @execution_graph.setter
    def execution_graph(self, execution_graph):
        """Sets the execution_graph of this Workspace.


        :param execution_graph: The execution_graph of this Workspace.  # noqa: E501
        :type: object
        """

        self._execution_graph = execution_graph

    @property
    def created_date(self):
        """Gets the created_date of this Workspace.  # noqa: E501


        :return: The created_date of this Workspace.  # noqa: E501
        :rtype: datetime
        """
        return self._created_date

    @created_date.setter
    def created_date(self, created_date):
        """Sets the created_date of this Workspace.


        :param created_date: The created_date of this Workspace.  # noqa: E501
        :type: datetime
        """

        self._created_date = created_date

    @property
    def updated_date(self):
        """Gets the updated_date of this Workspace.  # noqa: E501


        :return: The updated_date of this Workspace.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_date

    @updated_date.setter
    def updated_date(self, updated_date):
        """Sets the updated_date of this Workspace.


        :param updated_date: The updated_date of this Workspace.  # noqa: E501
        :type: datetime
        """

        self._updated_date = updated_date

    @property
    def user(self):
        """Gets the user of this Workspace.  # noqa: E501


        :return: The user of this Workspace.  # noqa: E501
        :rtype: int
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this Workspace.


        :param user: The user of this Workspace.  # noqa: E501
        :type: int
        """

        self._user = user

    @property
    def core_worker(self):
        """Gets the core_worker of this Workspace.  # noqa: E501


        :return: The core_worker of this Workspace.  # noqa: E501
        :rtype: int
        """
        return self._core_worker

    @core_worker.setter
    def core_worker(self, core_worker):
        """Sets the core_worker of this Workspace.


        :param core_worker: The core_worker of this Workspace.  # noqa: E501
        :type: int
        """

        self._core_worker = core_worker

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Workspace):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Workspace):
            return True

        return self.to_dict() != other.to_dict()
