# coding: utf-8

"""
    Autoppia

    Autoppia API Documentation  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@autoppia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from autoppia_backend_client.configuration import Configuration


class WorkerConfig(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'user_integration': 'list[ListUserIntegration]',
        'user_integration_ids': 'list[int]',
        'user_llm_model': 'UserLLMModel',
        'user_llm_model_id': 'int',
        'embedding_database': 'EmbeddingDatabase',
        'embedding_database_id': 'int',
        'system_prompt': 'Prompt',
        'system_prompt_id': 'int',
        'mcp': 'MCP',
        'mcp_id': 'int',
        'name': 'str',
        'template_id': 'str',
        'repo': 'str',
        'docker_image': 'str',
        'ip': 'str',
        'port': 'int',
        'whitelist': 'str',
        'arguments': 'str',
        'state': 'str',
        'avatar': 'str',
        'is_public': 'bool',
        'created_date': 'datetime',
        'updated_date': 'datetime',
        'user': 'int'
    }

    attribute_map = {
        'id': 'id',
        'user_integration': 'user_integration',
        'user_integration_ids': 'user_integration_ids',
        'user_llm_model': 'user_llm_model',
        'user_llm_model_id': 'user_llm_model_id',
        'embedding_database': 'embedding_database',
        'embedding_database_id': 'embedding_database_id',
        'system_prompt': 'system_prompt',
        'system_prompt_id': 'system_prompt_id',
        'mcp': 'mcp',
        'mcp_id': 'mcp_id',
        'name': 'name',
        'template_id': 'template_id',
        'repo': 'repo',
        'docker_image': 'docker_image',
        'ip': 'ip',
        'port': 'port',
        'whitelist': 'whitelist',
        'arguments': 'arguments',
        'state': 'state',
        'avatar': 'avatar',
        'is_public': 'is_public',
        'created_date': 'created_date',
        'updated_date': 'updated_date',
        'user': 'user'
    }

    def __init__(self, id=None, user_integration=None, user_integration_ids=None, user_llm_model=None, user_llm_model_id=None, embedding_database=None, embedding_database_id=None, system_prompt=None, system_prompt_id=None, mcp=None, mcp_id=None, name=None, template_id=None, repo=None, docker_image=None, ip=None, port=None, whitelist=None, arguments=None, state=None, avatar=None, is_public=None, created_date=None, updated_date=None, user=None, local_vars_configuration=None):  # noqa: E501
        """WorkerConfig - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._user_integration = None
        self._user_integration_ids = None
        self._user_llm_model = None
        self._user_llm_model_id = None
        self._embedding_database = None
        self._embedding_database_id = None
        self._system_prompt = None
        self._system_prompt_id = None
        self._mcp = None
        self._mcp_id = None
        self._name = None
        self._template_id = None
        self._repo = None
        self._docker_image = None
        self._ip = None
        self._port = None
        self._whitelist = None
        self._arguments = None
        self._state = None
        self._avatar = None
        self._is_public = None
        self._created_date = None
        self._updated_date = None
        self._user = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if user_integration is not None:
            self.user_integration = user_integration
        if user_integration_ids is not None:
            self.user_integration_ids = user_integration_ids
        if user_llm_model is not None:
            self.user_llm_model = user_llm_model
        if user_llm_model_id is not None:
            self.user_llm_model_id = user_llm_model_id
        if embedding_database is not None:
            self.embedding_database = embedding_database
        if embedding_database_id is not None:
            self.embedding_database_id = embedding_database_id
        if system_prompt is not None:
            self.system_prompt = system_prompt
        if system_prompt_id is not None:
            self.system_prompt_id = system_prompt_id
        if mcp is not None:
            self.mcp = mcp
        if mcp_id is not None:
            self.mcp_id = mcp_id
        self.name = name
        self.template_id = template_id
        self.repo = repo
        self.docker_image = docker_image
        self.ip = ip
        self.port = port
        self.whitelist = whitelist
        self.arguments = arguments
        if state is not None:
            self.state = state
        self.avatar = avatar
        if is_public is not None:
            self.is_public = is_public
        if created_date is not None:
            self.created_date = created_date
        if updated_date is not None:
            self.updated_date = updated_date
        self.user = user

    @property
    def id(self):
        """Gets the id of this WorkerConfig.  # noqa: E501


        :return: The id of this WorkerConfig.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this WorkerConfig.


        :param id: The id of this WorkerConfig.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def user_integration(self):
        """Gets the user_integration of this WorkerConfig.  # noqa: E501


        :return: The user_integration of this WorkerConfig.  # noqa: E501
        :rtype: list[ListUserIntegration]
        """
        return self._user_integration

    @user_integration.setter
    def user_integration(self, user_integration):
        """Sets the user_integration of this WorkerConfig.


        :param user_integration: The user_integration of this WorkerConfig.  # noqa: E501
        :type: list[ListUserIntegration]
        """

        self._user_integration = user_integration

    @property
    def user_integration_ids(self):
        """Gets the user_integration_ids of this WorkerConfig.  # noqa: E501


        :return: The user_integration_ids of this WorkerConfig.  # noqa: E501
        :rtype: list[int]
        """
        return self._user_integration_ids

    @user_integration_ids.setter
    def user_integration_ids(self, user_integration_ids):
        """Sets the user_integration_ids of this WorkerConfig.


        :param user_integration_ids: The user_integration_ids of this WorkerConfig.  # noqa: E501
        :type: list[int]
        """

        self._user_integration_ids = user_integration_ids

    @property
    def user_llm_model(self):
        """Gets the user_llm_model of this WorkerConfig.  # noqa: E501


        :return: The user_llm_model of this WorkerConfig.  # noqa: E501
        :rtype: UserLLMModel
        """
        return self._user_llm_model

    @user_llm_model.setter
    def user_llm_model(self, user_llm_model):
        """Sets the user_llm_model of this WorkerConfig.


        :param user_llm_model: The user_llm_model of this WorkerConfig.  # noqa: E501
        :type: UserLLMModel
        """

        self._user_llm_model = user_llm_model

    @property
    def user_llm_model_id(self):
        """Gets the user_llm_model_id of this WorkerConfig.  # noqa: E501


        :return: The user_llm_model_id of this WorkerConfig.  # noqa: E501
        :rtype: int
        """
        return self._user_llm_model_id

    @user_llm_model_id.setter
    def user_llm_model_id(self, user_llm_model_id):
        """Sets the user_llm_model_id of this WorkerConfig.


        :param user_llm_model_id: The user_llm_model_id of this WorkerConfig.  # noqa: E501
        :type: int
        """

        self._user_llm_model_id = user_llm_model_id

    @property
    def embedding_database(self):
        """Gets the embedding_database of this WorkerConfig.  # noqa: E501


        :return: The embedding_database of this WorkerConfig.  # noqa: E501
        :rtype: EmbeddingDatabase
        """
        return self._embedding_database

    @embedding_database.setter
    def embedding_database(self, embedding_database):
        """Sets the embedding_database of this WorkerConfig.


        :param embedding_database: The embedding_database of this WorkerConfig.  # noqa: E501
        :type: EmbeddingDatabase
        """

        self._embedding_database = embedding_database

    @property
    def embedding_database_id(self):
        """Gets the embedding_database_id of this WorkerConfig.  # noqa: E501


        :return: The embedding_database_id of this WorkerConfig.  # noqa: E501
        :rtype: int
        """
        return self._embedding_database_id

    @embedding_database_id.setter
    def embedding_database_id(self, embedding_database_id):
        """Sets the embedding_database_id of this WorkerConfig.


        :param embedding_database_id: The embedding_database_id of this WorkerConfig.  # noqa: E501
        :type: int
        """

        self._embedding_database_id = embedding_database_id

    @property
    def system_prompt(self):
        """Gets the system_prompt of this WorkerConfig.  # noqa: E501


        :return: The system_prompt of this WorkerConfig.  # noqa: E501
        :rtype: Prompt
        """
        return self._system_prompt

    @system_prompt.setter
    def system_prompt(self, system_prompt):
        """Sets the system_prompt of this WorkerConfig.


        :param system_prompt: The system_prompt of this WorkerConfig.  # noqa: E501
        :type: Prompt
        """

        self._system_prompt = system_prompt

    @property
    def system_prompt_id(self):
        """Gets the system_prompt_id of this WorkerConfig.  # noqa: E501


        :return: The system_prompt_id of this WorkerConfig.  # noqa: E501
        :rtype: int
        """
        return self._system_prompt_id

    @system_prompt_id.setter
    def system_prompt_id(self, system_prompt_id):
        """Sets the system_prompt_id of this WorkerConfig.


        :param system_prompt_id: The system_prompt_id of this WorkerConfig.  # noqa: E501
        :type: int
        """

        self._system_prompt_id = system_prompt_id

    @property
    def mcp(self):
        """Gets the mcp of this WorkerConfig.  # noqa: E501


        :return: The mcp of this WorkerConfig.  # noqa: E501
        :rtype: MCP
        """
        return self._mcp

    @mcp.setter
    def mcp(self, mcp):
        """Sets the mcp of this WorkerConfig.


        :param mcp: The mcp of this WorkerConfig.  # noqa: E501
        :type: MCP
        """

        self._mcp = mcp

    @property
    def mcp_id(self):
        """Gets the mcp_id of this WorkerConfig.  # noqa: E501


        :return: The mcp_id of this WorkerConfig.  # noqa: E501
        :rtype: int
        """
        return self._mcp_id

    @mcp_id.setter
    def mcp_id(self, mcp_id):
        """Sets the mcp_id of this WorkerConfig.


        :param mcp_id: The mcp_id of this WorkerConfig.  # noqa: E501
        :type: int
        """

        self._mcp_id = mcp_id

    @property
    def name(self):
        """Gets the name of this WorkerConfig.  # noqa: E501


        :return: The name of this WorkerConfig.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this WorkerConfig.


        :param name: The name of this WorkerConfig.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) > 255):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `255`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def template_id(self):
        """Gets the template_id of this WorkerConfig.  # noqa: E501


        :return: The template_id of this WorkerConfig.  # noqa: E501
        :rtype: str
        """
        return self._template_id

    @template_id.setter
    def template_id(self, template_id):
        """Sets the template_id of this WorkerConfig.


        :param template_id: The template_id of this WorkerConfig.  # noqa: E501
        :type: str
        """
        # template_id is optional - removed None validation
        if (self.local_vars_configuration.client_side_validation and
                template_id is not None and len(template_id) > 255):
            raise ValueError("Invalid value for `template_id`, length must be less than or equal to `255`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                template_id is not None and len(template_id) < 1):
            raise ValueError("Invalid value for `template_id`, length must be greater than or equal to `1`")  # noqa: E501

        self._template_id = template_id

    @property
    def repo(self):
        """Gets the repo of this WorkerConfig.  # noqa: E501


        :return: The repo of this WorkerConfig.  # noqa: E501
        :rtype: str
        """
        return self._repo

    @repo.setter
    def repo(self, repo):
        """Sets the repo of this WorkerConfig.


        :param repo: The repo of this WorkerConfig.  # noqa: E501
        :type: str
        """
        # repo is optional - removed None validation
        if (self.local_vars_configuration.client_side_validation and
                repo is not None and len(repo) > 255):
            raise ValueError("Invalid value for `repo`, length must be less than or equal to `255`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                repo is not None and len(repo) < 1):
            raise ValueError("Invalid value for `repo`, length must be greater than or equal to `1`")  # noqa: E501

        self._repo = repo

    @property
    def docker_image(self):
        """Gets the docker_image of this WorkerConfig.  # noqa: E501


        :return: The docker_image of this WorkerConfig.  # noqa: E501
        :rtype: str
        """
        return self._docker_image

    @docker_image.setter
    def docker_image(self, docker_image):
        """Sets the docker_image of this WorkerConfig.


        :param docker_image: The docker_image of this WorkerConfig.  # noqa: E501
        :type: str
        """
        # docker_image is optional - removed None validation
        if (self.local_vars_configuration.client_side_validation and
                docker_image is not None and len(docker_image) > 255):
            raise ValueError("Invalid value for `docker_image`, length must be less than or equal to `255`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                docker_image is not None and len(docker_image) < 1):
            raise ValueError("Invalid value for `docker_image`, length must be greater than or equal to `1`")  # noqa: E501

        self._docker_image = docker_image

    @property
    def ip(self):
        """Gets the ip of this WorkerConfig.  # noqa: E501


        :return: The ip of this WorkerConfig.  # noqa: E501
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """Sets the ip of this WorkerConfig.


        :param ip: The ip of this WorkerConfig.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                ip is not None and len(ip) > 255):
            raise ValueError("Invalid value for `ip`, length must be less than or equal to `255`")  # noqa: E501

        self._ip = ip

    @property
    def port(self):
        """Gets the port of this WorkerConfig.  # noqa: E501


        :return: The port of this WorkerConfig.  # noqa: E501
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this WorkerConfig.


        :param port: The port of this WorkerConfig.  # noqa: E501
        :type: int
        """
        if (self.local_vars_configuration.client_side_validation and
                port is not None and port > 2147483647):  # noqa: E501
            raise ValueError("Invalid value for `port`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                port is not None and port < -2147483648):  # noqa: E501
            raise ValueError("Invalid value for `port`, must be a value greater than or equal to `-2147483648`")  # noqa: E501

        self._port = port

    @property
    def whitelist(self):
        """Gets the whitelist of this WorkerConfig.  # noqa: E501


        :return: The whitelist of this WorkerConfig.  # noqa: E501
        :rtype: str
        """
        return self._whitelist

    @whitelist.setter
    def whitelist(self, whitelist):
        """Sets the whitelist of this WorkerConfig.


        :param whitelist: The whitelist of this WorkerConfig.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                whitelist is not None and len(whitelist) > 255):
            raise ValueError("Invalid value for `whitelist`, length must be less than or equal to `255`")  # noqa: E501

        self._whitelist = whitelist

    @property
    def arguments(self):
        """Gets the arguments of this WorkerConfig.  # noqa: E501


        :return: The arguments of this WorkerConfig.  # noqa: E501
        :rtype: str
        """
        return self._arguments

    @arguments.setter
    def arguments(self, arguments):
        """Sets the arguments of this WorkerConfig.


        :param arguments: The arguments of this WorkerConfig.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                arguments is not None and len(arguments) > 255):
            raise ValueError("Invalid value for `arguments`, length must be less than or equal to `255`")  # noqa: E501

        self._arguments = arguments

    @property
    def state(self):
        """Gets the state of this WorkerConfig.  # noqa: E501


        :return: The state of this WorkerConfig.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this WorkerConfig.


        :param state: The state of this WorkerConfig.  # noqa: E501
        :type: str
        """
        allowed_values = ["Deploying", "Running", "Stopped", "Terminated"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and state not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"  # noqa: E501
                .format(state, allowed_values)
            )

        self._state = state

    @property
    def avatar(self):
        """Gets the avatar of this WorkerConfig.  # noqa: E501


        :return: The avatar of this WorkerConfig.  # noqa: E501
        :rtype: str
        """
        return self._avatar

    @avatar.setter
    def avatar(self, avatar):
        """Sets the avatar of this WorkerConfig.


        :param avatar: The avatar of this WorkerConfig.  # noqa: E501
        :type: str
        """

        self._avatar = avatar

    @property
    def is_public(self):
        """Gets the is_public of this WorkerConfig.  # noqa: E501


        :return: The is_public of this WorkerConfig.  # noqa: E501
        :rtype: bool
        """
        return self._is_public

    @is_public.setter
    def is_public(self, is_public):
        """Sets the is_public of this WorkerConfig.


        :param is_public: The is_public of this WorkerConfig.  # noqa: E501
        :type: bool
        """

        self._is_public = is_public

    @property
    def created_date(self):
        """Gets the created_date of this WorkerConfig.  # noqa: E501


        :return: The created_date of this WorkerConfig.  # noqa: E501
        :rtype: datetime
        """
        return self._created_date

    @created_date.setter
    def created_date(self, created_date):
        """Sets the created_date of this WorkerConfig.


        :param created_date: The created_date of this WorkerConfig.  # noqa: E501
        :type: datetime
        """

        self._created_date = created_date

    @property
    def updated_date(self):
        """Gets the updated_date of this WorkerConfig.  # noqa: E501


        :return: The updated_date of this WorkerConfig.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_date

    @updated_date.setter
    def updated_date(self, updated_date):
        """Sets the updated_date of this WorkerConfig.


        :param updated_date: The updated_date of this WorkerConfig.  # noqa: E501
        :type: datetime
        """

        self._updated_date = updated_date

    @property
    def user(self):
        """Gets the user of this WorkerConfig.  # noqa: E501


        :return: The user of this WorkerConfig.  # noqa: E501
        :rtype: int
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this WorkerConfig.


        :param user: The user of this WorkerConfig.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and user is None:  # noqa: E501
            raise ValueError("Invalid value for `user`, must not be `None`")  # noqa: E501

        self._user = user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkerConfig):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, WorkerConfig):
            return True

        return self.to_dict() != other.to_dict()
